
namespace TinyWars.Utility {
    export const enum ClientErrorCode {
        NoError             = 0,

        BwWarBaseInit00    = 1000000,
        BwWarBaseInit01,

        ScwWarInit00,

        SfwWarInit00,

        SrwWarInit00,

        McwWarInit00,

        MrwWarInit00,

        MfwWarInit00,

        TwWarInitByMapRawData00,

        BwDrawVoteManagerInit00,

        BwCommonSettingManagerInit00,
        BwCommonSettingManagerInit01,
        BwCommonSettingManagerInit02,

        MeCommonSettingManagerInit00,
        MeCommonSettingManagerInit01,
        MeCommonSettingManagerInit02,

        BwFieldInit00,
        BwFieldInit01,
        BwFieldInit02,
        BwFieldInit03,

        BwUnitMapInit00,
        BwUnitMapInit01,
        BwUnitMapInit02,
        BwUnitMapInit03,
        BwUnitMapInit04,
        BwUnitMapInit05,
        BwUnitMapInit06,
        BwUnitMapInit07,
        BwUnitMapInit08,
        BwUnitMapInit09,
        BwUnitMapInit10,
        BwUnitMapInit11,
        BwUnitMapInit12,
        BwUnitMapInit13,
        BwUnitMapInit14,
        BwUnitMapInit15,

        BwUnitInit00,
        BwUnitInit01,
        BwUnitInit02,
        BwUnitInit03,
        BwUnitInit04,
        BwUnitInit05,

        BwTileMapInit00,
        BwTileMapInit01,
        BwTileMapInit02,
        BwTileMapInit03,
        BwTileMapInit04,
        BwTileMapInit05,
        BwTileMapInit06,

        BwTileDeserialize00,
        BwTileDeserialize01,
        BwTileDeserialize02,
        BwTileDeserialize03,
        BwTileDeserialize04,
        BwTileDeserialize05,
        BwTileDeserialize06,
        BwTileDeserialize07,
        BwTileDeserialize08,
        BwTileDeserialize09,
        BwTileDeserialize10,
        BwTileDeserialize11,
        BwTileDeserialize12,
        BwTileDeserialize13,
        BwTileDeserialize14,

        BwFogMapInit00,
        BwFogMapInit01,
        BwFogMapInit02,
        BwFogMapInit03,
        BwFogMapInit04,
        BwFogMapInit05,
        BwFogMapInit06,
        BwFogMapInit07,

        BwFogMapResetMapFromPath00,
        BwFogMapResetMapFromPath01,
        BwFogMapResetMapFromPath02,
        BwFogMapResetMapFromPath03,

        BwPlayerInit00,
        BwPlayerInit01,
        BwPlayerInit02,
        BwPlayerInit03,
        BwPlayerInit04,
        BwPlayerInit05,
        BwPlayerInit06,
        BwPlayerInit07,
        BwPlayerInit08,
        BwPlayerInit09,
        BwPlayerInit10,
        BwPlayerInit11,
        BwPlayerInit12,

        BwPlayerManagerInit00,
        BwPlayerManagerInit01,
        BwPlayerManagerInit02,
        BwPlayerManagerInit03,
        BwPlayerManagerInit04,
        BwPlayerManagerInit05,
        BwPlayerManagerInit06,

        BwTurnManagerInit00,
        BwTurnManagerInit01,
        BwTurnManagerInit02,
        BwTurnManagerInit03,
        BwTurnManagerInit04,

        BwRandomNumberManager00,
        BwRandomNumberManager01,

        MapRawDataValidation00,
        MapRawDataValidation01,
        MapRawDataValidation02,
        MapRawDataValidation03,
        MapRawDataValidation04,
        MapRawDataValidation05,
        MapRawDataValidation06,
        MapRawDataValidation07,
        MapRawDataValidation08,

        WarEventFullDataValidation00,
        WarEventFullDataValidation01,
        WarEventFullDataValidation02,
        WarEventFullDataValidation03,
        WarEventFullDataValidation04,
        WarEventFullDataValidation05,
        WarEventFullDataValidation06,
        WarEventFullDataValidation07,
        WarEventFullDataValidation08,
        WarEventFullDataValidation09,
        WarEventFullDataValidation10,
        WarEventFullDataValidation11,
        WarEventFullDataValidation12,
        WarEventFullDataValidation13,
        WarEventFullDataValidation14,
        WarEventFullDataValidation15,
        WarEventFullDataValidation16,

        WarRuleValidation00,
        WarRuleValidation01,
        WarRuleValidation02,
        WarRuleValidation03,
        WarRuleValidation04,
        WarRuleValidation05,
        WarRuleValidation06,

        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_00,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_01,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_02,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_03,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_04,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_05,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_06,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_07,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_08,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_09,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_10,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_11,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_12,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_13,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_14,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_15,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_16,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_17,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_18,
        BwWarRuleHelper_GetErrorCodeForRuleForPlayers_19,

        WarRuleGlobalParamsValidation00,

        UnitDataValidation00,
        UnitDataValidation01,
        UnitDataValidation02,
        UnitDataValidation03,
        UnitDataValidation04,
        UnitDataValidation05,
        UnitDataValidation06,
        UnitDataValidation07,
        UnitDataValidation08,
        UnitDataValidation09,
        UnitDataValidation10,
        UnitDataValidation11,
        UnitDataValidation12,
        UnitDataValidation13,
        UnitDataValidation14,
        UnitDataValidation15,
        UnitDataValidation16,

        SpwRobot_GetCommonParams_00,
        SpwRobot_GetCommonParams_01,
        SpwRobot_GetCommonParams_02,
        SpwRobot_GetCommonParams_03,
        SpwRobot_GetCommonParams_04,
        SpwRobot_GetCommonParams_05,
        SpwRobot_GetCommonParams_06,
        SpwRobot_GetCommonParams_07,
        SpwRobot_GetCommonParams_08,
        SpwRobot_GetCommonParams_09,

        SpwRobot_GetUnitValues_00,
        SpwRobot_GetUnitValues_01,
        SpwRobot_GetUnitValues_02,
        SpwRobot_GetUnitValues_03,
        SpwRobot_GetUnitValues_04,
        SpwRobot_GetUnitValues_05,
        SpwRobot_GetUnitValues_06,
        SpwRobot_GetUnitValues_07,
        SpwRobot_GetUnitValues_08,
        SpwRobot_GetUnitValues_09,

        SpwRobot_GetUnitValueRatio_00,
        SpwRobot_GetUnitValueRatio_01,
        SpwRobot_GetUnitValueRatio_02,
        SpwRobot_GetUnitValueRatio_03,
        SpwRobot_GetUnitValueRatio_04,
        SpwRobot_GetUnitValueRatio_05,
        SpwRobot_GetUnitValueRatio_06,
        SpwRobot_GetUnitValueRatio_07,
        SpwRobot_GetUnitValueRatio_08,
        SpwRobot_GetUnitValueRatio_09,

        SpwRobot_CheckCanUnitWaitOnGrid_00,
        SpwRobot_CheckCanUnitWaitOnGrid_01,
        SpwRobot_CheckCanUnitWaitOnGrid_02,
        SpwRobot_CheckCanUnitWaitOnGrid_03,
        SpwRobot_CheckCanUnitWaitOnGrid_04,
        SpwRobot_CheckCanUnitWaitOnGrid_05,
        SpwRobot_CheckCanUnitWaitOnGrid_06,
        SpwRobot_CheckCanUnitWaitOnGrid_07,
        SpwRobot_CheckCanUnitWaitOnGrid_08,
        SpwRobot_CheckCanUnitWaitOnGrid_09,

        SpwRobot_GetReachableArea_00,
        SpwRobot_GetReachableArea_01,
        SpwRobot_GetReachableArea_02,
        SpwRobot_GetReachableArea_03,
        SpwRobot_GetReachableArea_04,
        SpwRobot_GetReachableArea_05,
        SpwRobot_GetReachableArea_06,
        SpwRobot_GetReachableArea_07,
        SpwRobot_GetReachableArea_08,
        SpwRobot_GetReachableArea_09,

        SpwRobot_GetBestScoreAndActionForUnitAndPath_00,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_01,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_02,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_03,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_04,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_05,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_06,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_07,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_08,
        SpwRobot_GetBestScoreAndActionForUnitAndPath_09,

        SpwRobot_GetGlobalOffenseBonuses_00,
        SpwRobot_GetGlobalOffenseBonuses_01,
        SpwRobot_GetGlobalOffenseBonuses_02,
        SpwRobot_GetGlobalOffenseBonuses_03,
        SpwRobot_GetGlobalOffenseBonuses_04,
        SpwRobot_GetGlobalOffenseBonuses_05,
        SpwRobot_GetGlobalOffenseBonuses_06,
        SpwRobot_GetGlobalOffenseBonuses_07,
        SpwRobot_GetGlobalOffenseBonuses_08,
        SpwRobot_GetGlobalOffenseBonuses_09,

        SpwRobot_GetGlobalDefenseBonuses_00,
        SpwRobot_GetGlobalDefenseBonuses_01,
        SpwRobot_GetGlobalDefenseBonuses_02,
        SpwRobot_GetGlobalDefenseBonuses_03,
        SpwRobot_GetGlobalDefenseBonuses_04,
        SpwRobot_GetGlobalDefenseBonuses_05,
        SpwRobot_GetGlobalDefenseBonuses_06,
        SpwRobot_GetGlobalDefenseBonuses_07,
        SpwRobot_GetGlobalDefenseBonuses_08,
        SpwRobot_GetGlobalDefenseBonuses_09,

        SpwRobot_CreateDamageMap_00,
        SpwRobot_CreateDamageMap_01,
        SpwRobot_CreateDamageMap_02,
        SpwRobot_CreateDamageMap_03,
        SpwRobot_CreateDamageMap_04,
        SpwRobot_CreateDamageMap_05,
        SpwRobot_CreateDamageMap_06,
        SpwRobot_CreateDamageMap_07,
        SpwRobot_CreateDamageMap_08,
        SpwRobot_CreateDamageMap_09,

        SpwRobot_GetAttackInfo_00,
        SpwRobot_GetAttackInfo_01,
        SpwRobot_GetAttackInfo_02,
        SpwRobot_GetAttackInfo_03,
        SpwRobot_GetAttackInfo_04,
        SpwRobot_GetAttackInfo_05,
        SpwRobot_GetAttackInfo_06,
        SpwRobot_GetAttackInfo_07,
        SpwRobot_GetAttackInfo_08,
        SpwRobot_GetAttackInfo_09,

        SpwRobot_GetLuckValue_00,
        SpwRobot_GetLuckValue_01,
        SpwRobot_GetLuckValue_02,
        SpwRobot_GetLuckValue_03,
        SpwRobot_GetLuckValue_04,
        SpwRobot_GetLuckValue_05,
        SpwRobot_GetLuckValue_06,
        SpwRobot_GetLuckValue_07,
        SpwRobot_GetLuckValue_08,
        SpwRobot_GetLuckValue_09,

        SpwRobot_GetScoreForThreat_00,
        SpwRobot_GetScoreForThreat_01,
        SpwRobot_GetScoreForThreat_02,
        SpwRobot_GetScoreForThreat_03,
        SpwRobot_GetScoreForThreat_04,
        SpwRobot_GetScoreForThreat_05,
        SpwRobot_GetScoreForThreat_06,
        SpwRobot_GetScoreForThreat_07,
        SpwRobot_GetScoreForThreat_08,
        SpwRobot_GetScoreForThreat_09,

        SpwRobot_GetScoreForDistanceToCapturableBuildings_00,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_01,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_02,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_03,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_04,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_05,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_06,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_07,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_08,
        SpwRobot_GetScoreForDistanceToCapturableBuildings_09,

        SpwRobot_GetScoreForDistanceToOtherUnits_00,
        SpwRobot_GetScoreForDistanceToOtherUnits_01,
        SpwRobot_GetScoreForDistanceToOtherUnits_02,
        SpwRobot_GetScoreForDistanceToOtherUnits_03,
        SpwRobot_GetScoreForDistanceToOtherUnits_04,
        SpwRobot_GetScoreForDistanceToOtherUnits_05,
        SpwRobot_GetScoreForDistanceToOtherUnits_06,
        SpwRobot_GetScoreForDistanceToOtherUnits_07,
        SpwRobot_GetScoreForDistanceToOtherUnits_08,
        SpwRobot_GetScoreForDistanceToOtherUnits_09,

        SpwRobot_GetScoreForPosition_00,
        SpwRobot_GetScoreForPosition_01,
        SpwRobot_GetScoreForPosition_02,
        SpwRobot_GetScoreForPosition_03,
        SpwRobot_GetScoreForPosition_04,
        SpwRobot_GetScoreForPosition_05,
        SpwRobot_GetScoreForPosition_06,
        SpwRobot_GetScoreForPosition_07,
        SpwRobot_GetScoreForPosition_08,
        SpwRobot_GetScoreForPosition_09,

        SpwRobot_GetScoreForMovePath_00,
        SpwRobot_GetScoreForMovePath_01,
        SpwRobot_GetScoreForMovePath_02,
        SpwRobot_GetScoreForMovePath_03,
        SpwRobot_GetScoreForMovePath_04,
        SpwRobot_GetScoreForMovePath_05,
        SpwRobot_GetScoreForMovePath_06,
        SpwRobot_GetScoreForMovePath_07,
        SpwRobot_GetScoreForMovePath_08,
        SpwRobot_GetScoreForMovePath_09,

        SpwRobot_GetScoreForActionUnitBeLoaded_00,
        SpwRobot_GetScoreForActionUnitBeLoaded_01,
        SpwRobot_GetScoreForActionUnitBeLoaded_02,
        SpwRobot_GetScoreForActionUnitBeLoaded_03,
        SpwRobot_GetScoreForActionUnitBeLoaded_04,
        SpwRobot_GetScoreForActionUnitBeLoaded_05,
        SpwRobot_GetScoreForActionUnitBeLoaded_06,
        SpwRobot_GetScoreForActionUnitBeLoaded_07,
        SpwRobot_GetScoreForActionUnitBeLoaded_08,
        SpwRobot_GetScoreForActionUnitBeLoaded_09,

        SpwRobot_GetScoreForActionUnitJoin_00,
        SpwRobot_GetScoreForActionUnitJoin_01,
        SpwRobot_GetScoreForActionUnitJoin_02,
        SpwRobot_GetScoreForActionUnitJoin_03,
        SpwRobot_GetScoreForActionUnitJoin_04,
        SpwRobot_GetScoreForActionUnitJoin_05,
        SpwRobot_GetScoreForActionUnitJoin_06,
        SpwRobot_GetScoreForActionUnitJoin_07,
        SpwRobot_GetScoreForActionUnitJoin_08,
        SpwRobot_GetScoreForActionUnitJoin_09,

        SpwRobot_GetScoreForActionUnitAttack_00,
        SpwRobot_GetScoreForActionUnitAttack_01,
        SpwRobot_GetScoreForActionUnitAttack_02,
        SpwRobot_GetScoreForActionUnitAttack_03,
        SpwRobot_GetScoreForActionUnitAttack_04,
        SpwRobot_GetScoreForActionUnitAttack_05,
        SpwRobot_GetScoreForActionUnitAttack_06,
        SpwRobot_GetScoreForActionUnitAttack_07,
        SpwRobot_GetScoreForActionUnitAttack_08,
        SpwRobot_GetScoreForActionUnitAttack_09,
        SpwRobot_GetScoreForActionUnitAttack_10,
        SpwRobot_GetScoreForActionUnitAttack_11,
        SpwRobot_GetScoreForActionUnitAttack_12,
        SpwRobot_GetScoreForActionUnitAttack_13,
        SpwRobot_GetScoreForActionUnitAttack_14,
        SpwRobot_GetScoreForActionUnitAttack_15,
        SpwRobot_GetScoreForActionUnitAttack_16,
        SpwRobot_GetScoreForActionUnitAttack_17,
        SpwRobot_GetScoreForActionUnitAttack_18,
        SpwRobot_GetScoreForActionUnitAttack_19,

        SpwRobot_GetScoreForActionUnitCaptureTile_00,
        SpwRobot_GetScoreForActionUnitCaptureTile_01,
        SpwRobot_GetScoreForActionUnitCaptureTile_02,
        SpwRobot_GetScoreForActionUnitCaptureTile_03,
        SpwRobot_GetScoreForActionUnitCaptureTile_04,
        SpwRobot_GetScoreForActionUnitCaptureTile_05,
        SpwRobot_GetScoreForActionUnitCaptureTile_06,
        SpwRobot_GetScoreForActionUnitCaptureTile_07,
        SpwRobot_GetScoreForActionUnitCaptureTile_08,
        SpwRobot_GetScoreForActionUnitCaptureTile_09,

        SpwRobot_GetScoreForActionUnitDive_00,
        SpwRobot_GetScoreForActionUnitDive_01,
        SpwRobot_GetScoreForActionUnitDive_02,
        SpwRobot_GetScoreForActionUnitDive_03,
        SpwRobot_GetScoreForActionUnitDive_04,
        SpwRobot_GetScoreForActionUnitDive_05,
        SpwRobot_GetScoreForActionUnitDive_06,
        SpwRobot_GetScoreForActionUnitDive_07,
        SpwRobot_GetScoreForActionUnitDive_08,
        SpwRobot_GetScoreForActionUnitDive_09,

        SpwRobot_GetScoreForUnitLaunchFlare_00,
        SpwRobot_GetScoreForUnitLaunchFlare_01,
        SpwRobot_GetScoreForUnitLaunchFlare_02,
        SpwRobot_GetScoreForUnitLaunchFlare_03,
        SpwRobot_GetScoreForUnitLaunchFlare_04,
        SpwRobot_GetScoreForUnitLaunchFlare_05,
        SpwRobot_GetScoreForUnitLaunchFlare_06,
        SpwRobot_GetScoreForUnitLaunchFlare_07,
        SpwRobot_GetScoreForUnitLaunchFlare_08,
        SpwRobot_GetScoreForUnitLaunchFlare_09,

        SpwRobot_GetScoreForActionUnitSurface_00,
        SpwRobot_GetScoreForActionUnitSurface_01,
        SpwRobot_GetScoreForActionUnitSurface_02,
        SpwRobot_GetScoreForActionUnitSurface_03,
        SpwRobot_GetScoreForActionUnitSurface_04,
        SpwRobot_GetScoreForActionUnitSurface_05,
        SpwRobot_GetScoreForActionUnitSurface_06,
        SpwRobot_GetScoreForActionUnitSurface_07,
        SpwRobot_GetScoreForActionUnitSurface_08,
        SpwRobot_GetScoreForActionUnitSurface_09,

        SpwRobot_GetScoreForActionPlayerProduceUnit_00,
        SpwRobot_GetScoreForActionPlayerProduceUnit_01,
        SpwRobot_GetScoreForActionPlayerProduceUnit_02,
        SpwRobot_GetScoreForActionPlayerProduceUnit_03,
        SpwRobot_GetScoreForActionPlayerProduceUnit_04,
        SpwRobot_GetScoreForActionPlayerProduceUnit_05,
        SpwRobot_GetScoreForActionPlayerProduceUnit_06,
        SpwRobot_GetScoreForActionPlayerProduceUnit_07,
        SpwRobot_GetScoreForActionPlayerProduceUnit_08,
        SpwRobot_GetScoreForActionPlayerProduceUnit_09,
        SpwRobot_GetScoreForActionPlayerProduceUnit_10,
        SpwRobot_GetScoreForActionPlayerProduceUnit_11,
        SpwRobot_GetScoreForActionPlayerProduceUnit_12,
        SpwRobot_GetScoreForActionPlayerProduceUnit_13,
        SpwRobot_GetScoreForActionPlayerProduceUnit_14,
        SpwRobot_GetScoreForActionPlayerProduceUnit_15,
        SpwRobot_GetScoreForActionPlayerProduceUnit_16,
        SpwRobot_GetScoreForActionPlayerProduceUnit_17,
        SpwRobot_GetScoreForActionPlayerProduceUnit_18,
        SpwRobot_GetScoreForActionPlayerProduceUnit_19,

        SpwRobot_GetScoreAndActionUnitBeLoaded_00,
        SpwRobot_GetScoreAndActionUnitBeLoaded_01,
        SpwRobot_GetScoreAndActionUnitBeLoaded_02,
        SpwRobot_GetScoreAndActionUnitBeLoaded_03,
        SpwRobot_GetScoreAndActionUnitBeLoaded_04,
        SpwRobot_GetScoreAndActionUnitBeLoaded_05,
        SpwRobot_GetScoreAndActionUnitBeLoaded_06,
        SpwRobot_GetScoreAndActionUnitBeLoaded_07,
        SpwRobot_GetScoreAndActionUnitBeLoaded_08,
        SpwRobot_GetScoreAndActionUnitBeLoaded_09,

        SpwRobot_GetScoreAndActionUnitJoin_00,
        SpwRobot_GetScoreAndActionUnitJoin_01,
        SpwRobot_GetScoreAndActionUnitJoin_02,
        SpwRobot_GetScoreAndActionUnitJoin_03,
        SpwRobot_GetScoreAndActionUnitJoin_04,
        SpwRobot_GetScoreAndActionUnitJoin_05,
        SpwRobot_GetScoreAndActionUnitJoin_06,
        SpwRobot_GetScoreAndActionUnitJoin_07,
        SpwRobot_GetScoreAndActionUnitJoin_08,
        SpwRobot_GetScoreAndActionUnitJoin_09,

        SpwRobot_GetScoreAndActionUnitAttack_00,
        SpwRobot_GetScoreAndActionUnitAttack_01,
        SpwRobot_GetScoreAndActionUnitAttack_02,
        SpwRobot_GetScoreAndActionUnitAttack_03,
        SpwRobot_GetScoreAndActionUnitAttack_04,
        SpwRobot_GetScoreAndActionUnitAttack_05,
        SpwRobot_GetScoreAndActionUnitAttack_06,
        SpwRobot_GetScoreAndActionUnitAttack_07,
        SpwRobot_GetScoreAndActionUnitAttack_08,
        SpwRobot_GetScoreAndActionUnitAttack_09,

        SpwRobot_GetScoreAndActionUnitCaptureTile_00,
        SpwRobot_GetScoreAndActionUnitCaptureTile_01,
        SpwRobot_GetScoreAndActionUnitCaptureTile_02,
        SpwRobot_GetScoreAndActionUnitCaptureTile_03,
        SpwRobot_GetScoreAndActionUnitCaptureTile_04,
        SpwRobot_GetScoreAndActionUnitCaptureTile_05,
        SpwRobot_GetScoreAndActionUnitCaptureTile_06,
        SpwRobot_GetScoreAndActionUnitCaptureTile_07,
        SpwRobot_GetScoreAndActionUnitCaptureTile_08,
        SpwRobot_GetScoreAndActionUnitCaptureTile_09,

        SpwRobot_GetScoreAndActionUnitLaunchSilo_00,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_01,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_02,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_03,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_04,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_05,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_06,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_07,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_08,
        SpwRobot_GetScoreAndActionUnitLaunchSilo_09,

        SpwRobot_GetScoreAndActionUnitLaunchFlare_00,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_01,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_02,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_03,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_04,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_05,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_06,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_07,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_08,
        SpwRobot_GetScoreAndActionUnitLaunchFlare_09,

        SpwRobot_GetBestScoreAndActionForCandidateUnit_00,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_01,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_02,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_03,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_04,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_05,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_06,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_07,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_08,
        SpwRobot_GetBestScoreAndActionForCandidateUnit_09,

        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_00,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_01,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_02,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_03,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_04,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_05,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_06,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_07,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_08,
        SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_09,

        SpwRobot_GetScoreAndActionUnitDive_00,
        SpwRobot_GetScoreAndActionUnitDive_01,
        SpwRobot_GetScoreAndActionUnitDive_02,
        SpwRobot_GetScoreAndActionUnitDive_03,
        SpwRobot_GetScoreAndActionUnitDive_04,
        SpwRobot_GetScoreAndActionUnitDive_05,
        SpwRobot_GetScoreAndActionUnitDive_06,
        SpwRobot_GetScoreAndActionUnitDive_07,
        SpwRobot_GetScoreAndActionUnitDive_08,
        SpwRobot_GetScoreAndActionUnitDive_09,

        SpwRobot_GetScoreAndActionUnitSurface_00,
        SpwRobot_GetScoreAndActionUnitSurface_01,
        SpwRobot_GetScoreAndActionUnitSurface_02,
        SpwRobot_GetScoreAndActionUnitSurface_03,
        SpwRobot_GetScoreAndActionUnitSurface_04,
        SpwRobot_GetScoreAndActionUnitSurface_05,
        SpwRobot_GetScoreAndActionUnitSurface_06,
        SpwRobot_GetScoreAndActionUnitSurface_07,
        SpwRobot_GetScoreAndActionUnitSurface_08,
        SpwRobot_GetScoreAndActionUnitSurface_09,

        SpwRobot_GetScoreAndActionUnitWait_00,
        SpwRobot_GetScoreAndActionUnitWait_01,
        SpwRobot_GetScoreAndActionUnitWait_02,
        SpwRobot_GetScoreAndActionUnitWait_03,
        SpwRobot_GetScoreAndActionUnitWait_04,
        SpwRobot_GetScoreAndActionUnitWait_05,
        SpwRobot_GetScoreAndActionUnitWait_06,
        SpwRobot_GetScoreAndActionUnitWait_07,
        SpwRobot_GetScoreAndActionUnitWait_08,
        SpwRobot_GetScoreAndActionUnitWait_09,

        SpwRobot_GetBestActionPlayerProduceUnit_00,
        SpwRobot_GetBestActionPlayerProduceUnit_01,
        SpwRobot_GetBestActionPlayerProduceUnit_02,
        SpwRobot_GetBestActionPlayerProduceUnit_03,
        SpwRobot_GetBestActionPlayerProduceUnit_04,
        SpwRobot_GetBestActionPlayerProduceUnit_05,
        SpwRobot_GetBestActionPlayerProduceUnit_06,
        SpwRobot_GetBestActionPlayerProduceUnit_07,
        SpwRobot_GetBestActionPlayerProduceUnit_08,
        SpwRobot_GetBestActionPlayerProduceUnit_09,

        SpwRobot_GetNextAction_00,
        SpwRobot_GetNextAction_01,
        SpwRobot_GetNextAction_02,
        SpwRobot_GetNextAction_03,
        SpwRobot_GetNextAction_04,
        SpwRobot_GetNextAction_05,
        SpwRobot_GetNextAction_06,
        SpwRobot_GetNextAction_07,
        SpwRobot_GetNextAction_08,
        SpwRobot_GetNextAction_09,

        SpwRobot_DoGetNextAction_00,
        SpwRobot_DoGetNextAction_01,
        SpwRobot_DoGetNextAction_02,
        SpwRobot_DoGetNextAction_03,
        SpwRobot_DoGetNextAction_04,
        SpwRobot_DoGetNextAction_05,
        SpwRobot_DoGetNextAction_06,
        SpwRobot_DoGetNextAction_07,
        SpwRobot_DoGetNextAction_08,
        SpwRobot_DoGetNextAction_09,

        VisibilityHelpers_GetDiscoveredUnitsByPath_00,
        VisibilityHelpers_GetDiscoveredUnitsByPath_01,
        VisibilityHelpers_GetDiscoveredUnitsByPath_02,
        VisibilityHelpers_GetDiscoveredUnitsByPath_03,
        VisibilityHelpers_GetDiscoveredUnitsByPath_04,
        VisibilityHelpers_GetDiscoveredUnitsByPath_05,
        VisibilityHelpers_GetDiscoveredUnitsByPath_06,
        VisibilityHelpers_GetDiscoveredUnitsByPath_07,
        VisibilityHelpers_GetDiscoveredUnitsByPath_08,
        VisibilityHelpers_GetDiscoveredUnitsByPath_09,
    }
}
