
namespace TinyWars.Utility {
    export const enum ClientErrorCode {
        NoError             = 0,

        BwWarBaseInit00    = 1000000,
        BwWarBaseInit01,

        BwDrawVoteManagerInit00,

        BwCommonSettingManagerInit00,
        BwCommonSettingManagerInit01,
        BwCommonSettingManagerInit02,

        MeCommonSettingManagerInit00,
        MeCommonSettingManagerInit01,
        MeCommonSettingManagerInit02,

        BwFieldInit00,

        BwUnitMapInit00,
        BwUnitMapInit01,
        BwUnitMapInit02,
        BwUnitMapInit03,
        BwUnitMapInit04,
        BwUnitMapInit05,
        BwUnitMapInit06,
        BwUnitMapInit07,
        BwUnitMapInit08,
        BwUnitMapInit09,
        BwUnitMapInit10,
        BwUnitMapInit11,
        BwUnitMapInit12,
        BwUnitMapInit13,
        BwUnitMapInit14,

        BwUnitInit00,
        BwUnitInit01,
        BwUnitInit02,
        BwUnitInit03,
        BwUnitInit04,
        BwUnitInit05,

        WarRuleValidation00,
        WarRuleValidation01,
        WarRuleValidation02,
        WarRuleValidation03,
        WarRuleValidation04,
        WarRuleValidation05,
        WarRuleValidation06,

        PlayerRuleValidation00,
        PlayerRuleValidation01,
        PlayerRuleValidation02,
        PlayerRuleValidation03,
        PlayerRuleValidation04,
        PlayerRuleValidation05,
        PlayerRuleValidation06,
        PlayerRuleValidation07,
        PlayerRuleValidation08,
        PlayerRuleValidation09,
        PlayerRuleValidation10,
        PlayerRuleValidation11,
        PlayerRuleValidation12,
        PlayerRuleValidation13,
        PlayerRuleValidation14,

        WarRuleGlobalParamsValidation00,

        UnitDataValidation00,
        UnitDataValidation01,
        UnitDataValidation02,
        UnitDataValidation03,
        UnitDataValidation04,
        UnitDataValidation05,
        UnitDataValidation06,
        UnitDataValidation07,
        UnitDataValidation08,
        UnitDataValidation09,
        UnitDataValidation10,
        UnitDataValidation11,
        UnitDataValidation12,
        UnitDataValidation13,
        UnitDataValidation14,
        UnitDataValidation15,
        UnitDataValidation16,
    }
}
