
namespace TinyWars.Utility {
    export const enum ClientErrorCode {
        NoError             = 0,

        BwWarBaseInit00    = 1000000,
        BwWarBaseInit01,

        BwDrawVoteManagerInit00,

        BwCommonSettingManagerInit00,
        BwCommonSettingManagerInit01,
        BwCommonSettingManagerInit02,

        MeCommonSettingManagerInit00,
        MeCommonSettingManagerInit01,
        MeCommonSettingManagerInit02,

        BwFieldInit00,
        BwFieldInit01,
        BwFieldInit02,
        BwFieldInit03,

        BwUnitMapInit00,
        BwUnitMapInit01,
        BwUnitMapInit02,
        BwUnitMapInit03,
        BwUnitMapInit04,
        BwUnitMapInit05,
        BwUnitMapInit06,
        BwUnitMapInit07,
        BwUnitMapInit08,
        BwUnitMapInit09,
        BwUnitMapInit10,
        BwUnitMapInit11,
        BwUnitMapInit12,
        BwUnitMapInit13,
        BwUnitMapInit14,
        BwUnitMapInit15,

        BwUnitInit00,
        BwUnitInit01,
        BwUnitInit02,
        BwUnitInit03,
        BwUnitInit04,
        BwUnitInit05,

        BwTileMapInit00,
        BwTileMapInit01,
        BwTileMapInit02,
        BwTileMapInit03,
        BwTileMapInit04,
        BwTileMapInit05,
        BwTileMapInit06,

        BwTileDeserialize00,
        BwTileDeserialize01,
        BwTileDeserialize02,
        BwTileDeserialize03,
        BwTileDeserialize04,
        BwTileDeserialize05,
        BwTileDeserialize06,
        BwTileDeserialize07,
        BwTileDeserialize08,
        BwTileDeserialize09,
        BwTileDeserialize10,
        BwTileDeserialize11,
        BwTileDeserialize12,
        BwTileDeserialize13,
        BwTileDeserialize14,

        BwFogMapInit00,
        BwFogMapInit01,
        BwFogMapInit02,
        BwFogMapInit03,
        BwFogMapInit04,
        BwFogMapInit05,
        BwFogMapInit06,
        BwFogMapInit07,

        BwFogMapResetMapFromPath00,
        BwFogMapResetMapFromPath01,
        BwFogMapResetMapFromPath02,
        BwFogMapResetMapFromPath03,

        BwPlayerInit00,
        BwPlayerInit01,
        BwPlayerInit02,
        BwPlayerInit03,
        BwPlayerInit04,
        BwPlayerInit05,
        BwPlayerInit06,
        BwPlayerInit07,
        BwPlayerInit08,
        BwPlayerInit09,
        BwPlayerInit10,
        BwPlayerInit11,
        BwPlayerInit12,

        BwPlayerManagerInit00,
        BwPlayerManagerInit01,
        BwPlayerManagerInit02,
        BwPlayerManagerInit03,
        BwPlayerManagerInit04,
        BwPlayerManagerInit05,

        BwTurnManagerInit00,
        BwTurnManagerInit01,
        BwTurnManagerInit02,
        BwTurnManagerInit03,
        BwTurnManagerInit04,

        WarRuleValidation00,
        WarRuleValidation01,
        WarRuleValidation02,
        WarRuleValidation03,
        WarRuleValidation04,
        WarRuleValidation05,
        WarRuleValidation06,

        PlayerRuleValidation00,
        PlayerRuleValidation01,
        PlayerRuleValidation02,
        PlayerRuleValidation03,
        PlayerRuleValidation04,
        PlayerRuleValidation05,
        PlayerRuleValidation06,
        PlayerRuleValidation07,
        PlayerRuleValidation08,
        PlayerRuleValidation09,
        PlayerRuleValidation10,
        PlayerRuleValidation11,
        PlayerRuleValidation12,
        PlayerRuleValidation13,
        PlayerRuleValidation14,

        WarRuleGlobalParamsValidation00,

        UnitDataValidation00,
        UnitDataValidation01,
        UnitDataValidation02,
        UnitDataValidation03,
        UnitDataValidation04,
        UnitDataValidation05,
        UnitDataValidation06,
        UnitDataValidation07,
        UnitDataValidation08,
        UnitDataValidation09,
        UnitDataValidation10,
        UnitDataValidation11,
        UnitDataValidation12,
        UnitDataValidation13,
        UnitDataValidation14,
        UnitDataValidation15,
        UnitDataValidation16,
    }
}
