
namespace TinyWars.Utility {
export const enum ServerErrorCode {
    NoError = 0,

    ServerDisconnect0001,               // 服务器维护

    MpwManager0000,
    MpwManager0001,
    MpwManager0002,
    MpwManager0003,
    MpwManager0004,
    MpwManager0005,
    MpwManager0006,
    MpwManager0007,

    ReplayManager0000,
    ReplayManager0001,

    BwRandomNumberManager0000,
    BwRandomNumberManager0001,

    BwDrawVoteManagerInit0000,

    BwPlayerManagerInit0000,
    BwPlayerManagerInit0001,
    BwPlayerManagerInit0002,
    BwPlayerManagerInit0003,
    BwPlayerManagerInit0004,
    BwPlayerManagerInit0005,
    BwPlayerManagerInit0006,

    BwFogMapInit0000,
    BwFogMapInit0001,
    BwFogMapInit0002,
    BwFogMapInit0003,
    BwFogMapInit0004,
    BwFogMapInit0005,
    BwFogMapInit0006,
    BwFogMapInit0007,

    BwFogMapResetMapFromPath0000,
    BwFogMapResetMapFromPath0001,
    BwFogMapResetMapFromPath0002,
    BwFogMapResetMapFromPath0003,

    BwTileMapInit0000,
    BwTileMapInit0001,
    BwTileMapInit0002,
    BwTileMapInit0003,
    BwTileMapInit0004,
    BwTileMapInit0005,
    BwTileMapInit0006,

    BwUnitMapInit0000,
    BwUnitMapInit0001,
    BwUnitMapInit0002,
    BwUnitMapInit0003,
    BwUnitMapInit0004,
    BwUnitMapInit0005,
    BwUnitMapInit0006,
    BwUnitMapInit0007,
    BwUnitMapInit0008,
    BwUnitMapInit0009,
    BwUnitMapInit0010,
    BwUnitMapInit0011,
    BwUnitMapInit0012,
    BwUnitMapInit0013,
    BwUnitMapInit0014,
    BwUnitMapInit0015,
    BwUnitMapInit0016,
    BwUnitMapInit0017,

    BwUnitInit0000,
    BwUnitInit0001,
    BwUnitInit0002,
    BwUnitInit0003,
    BwUnitInit0004,
    BwUnitInit0005,

    BwTileDeserialize0000,
    BwTileDeserialize0001,
    BwTileDeserialize0002,
    BwTileDeserialize0003,
    BwTileDeserialize0004,
    BwTileDeserialize0005,
    BwTileDeserialize0006,
    BwTileDeserialize0007,
    BwTileDeserialize0008,
    BwTileDeserialize0009,
    BwTileDeserialize0010,
    BwTileDeserialize0011,
    BwTileDeserialize0012,
    BwTileDeserialize0013,
    BwTileDeserialize0014,

    BwPlayerInit0000,
    BwPlayerInit0001,
    BwPlayerInit0002,
    BwPlayerInit0003,
    BwPlayerInit0004,
    BwPlayerInit0005,
    BwPlayerInit0006,
    BwPlayerInit0007,
    BwPlayerInit0008,
    BwPlayerInit0009,
    BwPlayerInit0010,
    BwPlayerInit0011,
    BwPlayerInit0012,
    BwPlayerInit0013,

    BwFieldInit0000,
    BwFieldInit0001,
    BwFieldInit0002,
    BwFieldInit0003,

    BwCommonSettingManagerInit0000,
    BwCommonSettingManagerInit0001,
    BwCommonSettingManagerInit0002,
    BwCommonSettingManagerInit0003,
    BwCommonSettingManagerInit0004,
    BwCommonSettingManagerInit0005,
    BwCommonSettingManagerInit0006,
    BwCommonSettingManagerInit0007,
    BwCommonSettingManagerInit0008,
    BwCommonSettingManagerInit0009,
    BwCommonSettingManagerInit0010,
    BwCommonSettingManagerInit0011,
    BwCommonSettingManagerInit0012,
    BwCommonSettingManagerInit0013,

    BwTurnManagerInit0000,
    BwTurnManagerInit0001,
    BwTurnManagerInit0002,
    BwTurnManagerInit0003,
    BwTurnManagerInit0004,

    BwHelpers_GetRevisedPath_0000,
    BwHelpers_GetRevisedPath_0001,
    BwHelpers_GetRevisedPath_0002,
    BwHelpers_GetRevisedPath_0003,
    BwHelpers_GetRevisedPath_0004,
    BwHelpers_GetRevisedPath_0005,
    BwHelpers_GetRevisedPath_0006,
    BwHelpers_GetRevisedPath_0007,
    BwHelpers_GetRevisedPath_0008,
    BwHelpers_GetRevisedPath_0009,
    BwHelpers_GetRevisedPath_0010,
    BwHelpers_GetRevisedPath_0011,
    BwHelpers_GetRevisedPath_0012,
    BwHelpers_GetRevisedPath_0013,
    BwHelpers_GetRevisedPath_0014,
    BwHelpers_GetRevisedPath_0015,
    BwHelpers_GetRevisedPath_0016,
    BwHelpers_GetRevisedPath_0017,
    BwHelpers_GetRevisedPath_0018,
    BwHelpers_GetRevisedPath_0019,

    BwWarDataHelper_CreateInitialDataForMcw_0000,
    BwWarDataHelper_CreateInitialDataForMcw_0001,
    BwWarDataHelper_CreateInitialDataForMcw_0002,
    BwWarDataHelper_CreateInitialDataForMcw_0003,
    BwWarDataHelper_CreateInitialDataForMcw_0004,

    BwWarDataHelper_CreateInitialDataForMrw_0000,
    BwWarDataHelper_CreateInitialDataForMrw_0001,
    BwWarDataHelper_CreateInitialDataForMrw_0002,
    BwWarDataHelper_CreateInitialDataForMrw_0003,
    BwWarDataHelper_CreateInitialDataForMrw_0004,

    BwWarDataHelper_CreateInitialDataForMfw_0000,
    BwWarDataHelper_CreateInitialDataForMfw_0001,
    BwWarDataHelper_CreateInitialDataForMfw_0002,

    BwWarDataHelper_CreateInitialDataForScw_0000,
    BwWarDataHelper_CreateInitialDataForScw_0001,
    BwWarDataHelper_CreateInitialDataForScw_0002,

    BwWarDataHelper_CreateInitialDataForSrw_0000,
    BwWarDataHelper_CreateInitialDataForSrw_0001,
    BwWarDataHelper_CreateInitialDataForSrw_0002,
    BwWarDataHelper_CreateInitialDataForSrw_0003,
    BwWarDataHelper_CreateInitialDataForSrw_0004,
    BwWarDataHelper_CreateInitialDataForSrw_0005,
    BwWarDataHelper_CreateInitialDataForSrw_0006,

    BwWarDataHelper_CreateTestWarDataForMap_0000,

    BwWarDataHelper_CreateInitialFieldData_0000,

    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0000,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0001,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0002,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0003,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0004,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0005,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0006,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0007,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0008,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0009,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0010,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0011,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0012,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0013,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0014,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMcw_0015,

    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0000,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0001,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0002,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0003,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0004,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0005,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0006,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0007,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0008,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0009,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0010,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0011,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0012,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0013,
    BwWarDataHelper_CreateInitialPlayerManagerDataForMrw_0014,

    BwWarDataHelper_CreateInitialPlayerManagerDataForScw_0000,
    BwWarDataHelper_CreateInitialPlayerManagerDataForScw_0001,
    BwWarDataHelper_CreateInitialPlayerManagerDataForScw_0002,

    BwWarDataHelper_CreateInitialPlayerManagerDataForSrw_0000,
    BwWarDataHelper_CreateInitialPlayerManagerDataForSrw_0001,
    BwWarDataHelper_CreateInitialPlayerManagerDataForSrw_0002,

    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0000,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0001,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0002,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0003,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0004,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0005,
    BwWarDataHelper_CreateTestPlayerManagerDataForMap_0006,

    BwWarDataHelper_TrimSrwData_0000,
    BwWarDataHelper_TrimSrwData_0001,
    BwWarDataHelper_TrimSrwData_0002,
    BwWarDataHelper_TrimSrwData_0003,
    BwWarDataHelper_TrimSrwData_0004,
    BwWarDataHelper_TrimSrwData_0005,
    BwWarDataHelper_TrimSrwData_0006,
    BwWarDataHelper_TrimSrwData_0007,
    BwWarDataHelper_TrimSrwData_0008,
    BwWarDataHelper_TrimSrwData_0009,

    StoreForMapExtraData0000,
    StoreForMapExtraData0001,
    StoreForMapExtraData0002,

    StoreForMpwOngoingWar0000,
    StoreForMpwOngoingWar0001,

    StoreForReplay0000,
    StoreForReplay0001,
    StoreForReplay0002,
    StoreForReplay0003,

    StoreForScwOngoingWar0000,
    StoreForScwOngoingWar0001,

    StoreForSrwRanking_UpdateWithSrwData_0000,
    StoreForSrwRanking_UpdateWithSrwData_0001,
    StoreForSrwRanking_UpdateWithSrwData_0002,
    StoreForSrwRanking_UpdateWithSrwData_0003,
    StoreForSrwRanking_UpdateWithSrwData_0004,
    StoreForSrwRanking_UpdateWithSrwData_0005,
    StoreForSrwRanking_UpdateWithSrwData_0006,
    StoreForSrwRanking_UpdateWithSrwData_0007,
    StoreForSrwRanking_UpdateWithSrwData_0008,
    StoreForSrwRanking_UpdateWithSrwData_0009,
    StoreForSrwRanking_UpdateWithSrwData_0010,
    StoreForSrwRanking_UpdateWithSrwData_0011,
    StoreForSrwRanking_UpdateWithSrwData_0012,
    StoreForSrwRanking_UpdateWithSrwData_0013,
    StoreForSrwRanking_UpdateWithSrwData_0014,
    StoreForSrwRanking_UpdateWithSrwData_0015,
    StoreForSrwRanking_UpdateWithSrwData_0016,
    StoreForSrwRanking_UpdateWithSrwData_0017,
    StoreForSrwRanking_UpdateWithSrwData_0018,
    StoreForSrwRanking_UpdateWithSrwData_0019,

    User0000,
    User0001,

    UserManager0000,
    UserManager0001,
    UserManager0002,
    UserManager0003,
    UserManager0004,
    UserManager0005,
    UserManager0006,
    UserManager0007,
    UserManager0008,
    UserManager0009,
    UserManager0010,
    UserManager0011,

    MapManager0000,
    MapManager0001,
    MapManager0002,
    MapManager0003,
    MapManager0004,
    MapManager0005,
    MapManager0006,
    MapManager0007,
    MapManager0008,
    MapManager0009,
    MapManager0010,
    MapManager0011,
    MapManager0012,
    MapManager0013,
    MapManager0014,
    MapManager0015,
    MapManager0016,
    MapManager0017,

    McrManager0000,
    McrManager0001,
    McrManager0002,
    McrManager0003,
    McrManager0004,
    McrManager0005,
    McrManager0006,
    McrManager0007,
    McrManager0008,
    McrManager0009,
    McrManager0010,

    MfrManager0000,
    MfrManager0001,
    MfrManager0002,
    MfrManager0003,
    MfrManager0004,
    MfrManager0005,
    MfrManager0006,
    MfrManager0007,

    BwWarBaseInit0000,
    BwWarBaseInit0001,
    BwWarBaseInit0002,
    BwWarBaseInit0003,
    BwWarBaseInit0004,

    MrwWarInit0000,
    MrwWarInit0001,
    MrwWarInit0002,
    MrwWarInit0003,
    MrwWarInit0004,
    MrwWarInit0005,
    MrwWarInit0006,
    MrwWarInit0007,
    MrwWarInit0008,
    MrwWarInit0009,

    McwWarInit0000,
    McwWarInit0001,
    McwWarInit0002,
    McwWarInit0003,
    McwWarInit0004,
    McwWarInit0005,
    McwWarInit0006,
    McwWarInit0007,
    McwWarInit0008,
    McwWarInit0009,

    MfwWarInit0000,

    MpwWarBaseInit0000,

    TwWarInitByMapRawData0000,

    WarEventFullDataValidation0000,
    WarEventFullDataValidation0001,
    WarEventFullDataValidation0002,
    WarEventFullDataValidation0003,
    WarEventFullDataValidation0004,
    WarEventFullDataValidation0005,
    WarEventFullDataValidation0006,
    WarEventFullDataValidation0007,
    WarEventFullDataValidation0008,
    WarEventFullDataValidation0009,
    WarEventFullDataValidation0010,
    WarEventFullDataValidation0011,
    WarEventFullDataValidation0012,
    WarEventFullDataValidation0013,
    WarEventFullDataValidation0014,
    WarEventFullDataValidation0015,
    WarEventFullDataValidation0016,

    WarRuleValidation0000,
    WarRuleValidation0001,
    WarRuleValidation0002,
    WarRuleValidation0003,
    WarRuleValidation0004,
    WarRuleValidation0005,
    WarRuleValidation0006,
    WarRuleValidation0007,
    WarRuleValidation0008,
    WarRuleValidation0009,

    WarRuleGlobalParamsValidation0000,

    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0000,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0001,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0002,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0003,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0004,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0005,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0006,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0007,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0008,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0009,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0010,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0011,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0012,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0013,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0014,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0015,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0016,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0017,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0018,
    BwWarRuleHelper_GetErrorCodeForRuleForPlayers_0019,

    BwWarActionReviser_Revise_0000,
    BwWarActionReviser_Revise_0001,
    BwWarActionReviser_Revise_0002,
    BwWarActionReviser_Revise_0003,
    BwWarActionReviser_Revise_0004,
    BwWarActionReviser_Revise_0005,
    BwWarActionReviser_Revise_0006,
    BwWarActionReviser_Revise_0007,
    BwWarActionReviser_Revise_0008,
    BwWarActionReviser_Revise_0009,

    BwWarActionReviser_RevisePlayerDeleteUnit_0000,
    BwWarActionReviser_RevisePlayerDeleteUnit_0001,
    BwWarActionReviser_RevisePlayerDeleteUnit_0002,
    BwWarActionReviser_RevisePlayerDeleteUnit_0003,
    BwWarActionReviser_RevisePlayerDeleteUnit_0004,
    BwWarActionReviser_RevisePlayerDeleteUnit_0005,
    BwWarActionReviser_RevisePlayerDeleteUnit_0006,
    BwWarActionReviser_RevisePlayerDeleteUnit_0007,
    BwWarActionReviser_RevisePlayerDeleteUnit_0008,
    BwWarActionReviser_RevisePlayerDeleteUnit_0009,

    BwWarActionReviser_RevisePlayerEndTurn_0000,
    BwWarActionReviser_RevisePlayerEndTurn_0001,
    BwWarActionReviser_RevisePlayerEndTurn_0002,
    BwWarActionReviser_RevisePlayerEndTurn_0003,
    BwWarActionReviser_RevisePlayerEndTurn_0004,
    BwWarActionReviser_RevisePlayerEndTurn_0005,
    BwWarActionReviser_RevisePlayerEndTurn_0006,
    BwWarActionReviser_RevisePlayerEndTurn_0007,
    BwWarActionReviser_RevisePlayerEndTurn_0008,
    BwWarActionReviser_RevisePlayerEndTurn_0009,

    BwWarActionReviser_RevisePlayerSurrender_0000,
    BwWarActionReviser_RevisePlayerSurrender_0001,
    BwWarActionReviser_RevisePlayerSurrender_0002,
    BwWarActionReviser_RevisePlayerSurrender_0003,
    BwWarActionReviser_RevisePlayerSurrender_0004,
    BwWarActionReviser_RevisePlayerSurrender_0005,
    BwWarActionReviser_RevisePlayerSurrender_0006,
    BwWarActionReviser_RevisePlayerSurrender_0007,
    BwWarActionReviser_RevisePlayerSurrender_0008,
    BwWarActionReviser_RevisePlayerSurrender_0009,

    BwWarActionReviser_RevisePlayerVoteForDraw_0000,
    BwWarActionReviser_RevisePlayerVoteForDraw_0001,
    BwWarActionReviser_RevisePlayerVoteForDraw_0002,
    BwWarActionReviser_RevisePlayerVoteForDraw_0003,
    BwWarActionReviser_RevisePlayerVoteForDraw_0004,
    BwWarActionReviser_RevisePlayerVoteForDraw_0005,
    BwWarActionReviser_RevisePlayerVoteForDraw_0006,
    BwWarActionReviser_RevisePlayerVoteForDraw_0007,
    BwWarActionReviser_RevisePlayerVoteForDraw_0008,
    BwWarActionReviser_RevisePlayerVoteForDraw_0009,

    BwWarActionReviser_RevisePlayerProduceUnit_0000,
    BwWarActionReviser_RevisePlayerProduceUnit_0001,
    BwWarActionReviser_RevisePlayerProduceUnit_0002,
    BwWarActionReviser_RevisePlayerProduceUnit_0003,
    BwWarActionReviser_RevisePlayerProduceUnit_0004,
    BwWarActionReviser_RevisePlayerProduceUnit_0005,
    BwWarActionReviser_RevisePlayerProduceUnit_0006,
    BwWarActionReviser_RevisePlayerProduceUnit_0007,
    BwWarActionReviser_RevisePlayerProduceUnit_0008,
    BwWarActionReviser_RevisePlayerProduceUnit_0009,
    BwWarActionReviser_RevisePlayerProduceUnit_0010,
    BwWarActionReviser_RevisePlayerProduceUnit_0011,
    BwWarActionReviser_RevisePlayerProduceUnit_0012,
    BwWarActionReviser_RevisePlayerProduceUnit_0013,
    BwWarActionReviser_RevisePlayerProduceUnit_0014,
    BwWarActionReviser_RevisePlayerProduceUnit_0015,
    BwWarActionReviser_RevisePlayerProduceUnit_0016,
    BwWarActionReviser_RevisePlayerProduceUnit_0017,
    BwWarActionReviser_RevisePlayerProduceUnit_0018,
    BwWarActionReviser_RevisePlayerProduceUnit_0019,

    BwWarActionReviser_ReviseSystemBeginTurn_0000,
    BwWarActionReviser_ReviseSystemBeginTurn_0001,
    BwWarActionReviser_ReviseSystemBeginTurn_0002,
    BwWarActionReviser_ReviseSystemBeginTurn_0003,
    BwWarActionReviser_ReviseSystemBeginTurn_0004,
    BwWarActionReviser_ReviseSystemBeginTurn_0005,
    BwWarActionReviser_ReviseSystemBeginTurn_0006,
    BwWarActionReviser_ReviseSystemBeginTurn_0007,
    BwWarActionReviser_ReviseSystemBeginTurn_0008,
    BwWarActionReviser_ReviseSystemBeginTurn_0009,

    BwWarActionReviser_ReviseSystemCallWarEvent_0000,
    BwWarActionReviser_ReviseSystemCallWarEvent_0001,
    BwWarActionReviser_ReviseSystemCallWarEvent_0002,
    BwWarActionReviser_ReviseSystemCallWarEvent_0003,
    BwWarActionReviser_ReviseSystemCallWarEvent_0004,
    BwWarActionReviser_ReviseSystemCallWarEvent_0005,
    BwWarActionReviser_ReviseSystemCallWarEvent_0006,
    BwWarActionReviser_ReviseSystemCallWarEvent_0007,
    BwWarActionReviser_ReviseSystemCallWarEvent_0008,
    BwWarActionReviser_ReviseSystemCallWarEvent_0009,

    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0000,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0001,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0002,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0003,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0004,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0005,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0006,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0007,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0008,
    BwWarActionReviser_ReviseSystemDestroyPlayerForce_0009,

    BwWarActionReviser_ReviseSystemEndWar_0000,
    BwWarActionReviser_ReviseSystemEndWar_0001,
    BwWarActionReviser_ReviseSystemEndWar_0002,
    BwWarActionReviser_ReviseSystemEndWar_0003,
    BwWarActionReviser_ReviseSystemEndWar_0004,
    BwWarActionReviser_ReviseSystemEndWar_0005,
    BwWarActionReviser_ReviseSystemEndWar_0006,
    BwWarActionReviser_ReviseSystemEndWar_0007,
    BwWarActionReviser_ReviseSystemEndWar_0008,
    BwWarActionReviser_ReviseSystemEndWar_0009,

    BwWarActionReviser_ReviseUnitAttackUnit_0000,
    BwWarActionReviser_ReviseUnitAttackUnit_0001,
    BwWarActionReviser_ReviseUnitAttackUnit_0002,
    BwWarActionReviser_ReviseUnitAttackUnit_0003,
    BwWarActionReviser_ReviseUnitAttackUnit_0004,
    BwWarActionReviser_ReviseUnitAttackUnit_0005,
    BwWarActionReviser_ReviseUnitAttackUnit_0006,
    BwWarActionReviser_ReviseUnitAttackUnit_0007,
    BwWarActionReviser_ReviseUnitAttackUnit_0008,
    BwWarActionReviser_ReviseUnitAttackUnit_0009,

    BwWarActionReviser_ReviseUnitAttackTile_0000,
    BwWarActionReviser_ReviseUnitAttackTile_0001,
    BwWarActionReviser_ReviseUnitAttackTile_0002,
    BwWarActionReviser_ReviseUnitAttackTile_0003,
    BwWarActionReviser_ReviseUnitAttackTile_0004,
    BwWarActionReviser_ReviseUnitAttackTile_0005,
    BwWarActionReviser_ReviseUnitAttackTile_0006,
    BwWarActionReviser_ReviseUnitAttackTile_0007,
    BwWarActionReviser_ReviseUnitAttackTile_0008,
    BwWarActionReviser_ReviseUnitAttackTile_0009,

    BwWarActionReviser_ReviseUnitBeLoaded_0000,
    BwWarActionReviser_ReviseUnitBeLoaded_0001,
    BwWarActionReviser_ReviseUnitBeLoaded_0002,
    BwWarActionReviser_ReviseUnitBeLoaded_0003,
    BwWarActionReviser_ReviseUnitBeLoaded_0004,
    BwWarActionReviser_ReviseUnitBeLoaded_0005,
    BwWarActionReviser_ReviseUnitBeLoaded_0006,
    BwWarActionReviser_ReviseUnitBeLoaded_0007,
    BwWarActionReviser_ReviseUnitBeLoaded_0008,
    BwWarActionReviser_ReviseUnitBeLoaded_0009,

    BwWarActionReviser_ReviseUnitBuildTile_0000,
    BwWarActionReviser_ReviseUnitBuildTile_0001,
    BwWarActionReviser_ReviseUnitBuildTile_0002,
    BwWarActionReviser_ReviseUnitBuildTile_0003,
    BwWarActionReviser_ReviseUnitBuildTile_0004,
    BwWarActionReviser_ReviseUnitBuildTile_0005,
    BwWarActionReviser_ReviseUnitBuildTile_0006,
    BwWarActionReviser_ReviseUnitBuildTile_0007,
    BwWarActionReviser_ReviseUnitBuildTile_0008,
    BwWarActionReviser_ReviseUnitBuildTile_0009,

    BwWarActionReviser_ReviseUnitCaptureTile_0000,
    BwWarActionReviser_ReviseUnitCaptureTile_0001,
    BwWarActionReviser_ReviseUnitCaptureTile_0002,
    BwWarActionReviser_ReviseUnitCaptureTile_0003,
    BwWarActionReviser_ReviseUnitCaptureTile_0004,
    BwWarActionReviser_ReviseUnitCaptureTile_0005,
    BwWarActionReviser_ReviseUnitCaptureTile_0006,
    BwWarActionReviser_ReviseUnitCaptureTile_0007,
    BwWarActionReviser_ReviseUnitCaptureTile_0008,
    BwWarActionReviser_ReviseUnitCaptureTile_0009,

    BwWarActionReviser_ReviseUnitDive_0000,
    BwWarActionReviser_ReviseUnitDive_0001,
    BwWarActionReviser_ReviseUnitDive_0002,
    BwWarActionReviser_ReviseUnitDive_0003,
    BwWarActionReviser_ReviseUnitDive_0004,
    BwWarActionReviser_ReviseUnitDive_0005,
    BwWarActionReviser_ReviseUnitDive_0006,
    BwWarActionReviser_ReviseUnitDive_0007,
    BwWarActionReviser_ReviseUnitDive_0008,
    BwWarActionReviser_ReviseUnitDive_0009,

    BwWarActionReviser_ReviseUnitDropUnit_0000,
    BwWarActionReviser_ReviseUnitDropUnit_0001,
    BwWarActionReviser_ReviseUnitDropUnit_0002,
    BwWarActionReviser_ReviseUnitDropUnit_0003,
    BwWarActionReviser_ReviseUnitDropUnit_0004,
    BwWarActionReviser_ReviseUnitDropUnit_0005,
    BwWarActionReviser_ReviseUnitDropUnit_0006,
    BwWarActionReviser_ReviseUnitDropUnit_0007,
    BwWarActionReviser_ReviseUnitDropUnit_0008,
    BwWarActionReviser_ReviseUnitDropUnit_0009,

    BwWarActionReviser_ReviseUnitJoinUnit_0000,
    BwWarActionReviser_ReviseUnitJoinUnit_0001,
    BwWarActionReviser_ReviseUnitJoinUnit_0002,
    BwWarActionReviser_ReviseUnitJoinUnit_0003,
    BwWarActionReviser_ReviseUnitJoinUnit_0004,
    BwWarActionReviser_ReviseUnitJoinUnit_0005,
    BwWarActionReviser_ReviseUnitJoinUnit_0006,
    BwWarActionReviser_ReviseUnitJoinUnit_0007,
    BwWarActionReviser_ReviseUnitJoinUnit_0008,
    BwWarActionReviser_ReviseUnitJoinUnit_0009,

    BwWarActionReviser_ReviseUnitLaunchFlare_0000,
    BwWarActionReviser_ReviseUnitLaunchFlare_0001,
    BwWarActionReviser_ReviseUnitLaunchFlare_0002,
    BwWarActionReviser_ReviseUnitLaunchFlare_0003,
    BwWarActionReviser_ReviseUnitLaunchFlare_0004,
    BwWarActionReviser_ReviseUnitLaunchFlare_0005,
    BwWarActionReviser_ReviseUnitLaunchFlare_0006,
    BwWarActionReviser_ReviseUnitLaunchFlare_0007,
    BwWarActionReviser_ReviseUnitLaunchFlare_0008,
    BwWarActionReviser_ReviseUnitLaunchFlare_0009,

    BwWarActionReviser_ReviseUnitLaunchSilo_0000,
    BwWarActionReviser_ReviseUnitLaunchSilo_0001,
    BwWarActionReviser_ReviseUnitLaunchSilo_0002,
    BwWarActionReviser_ReviseUnitLaunchSilo_0003,
    BwWarActionReviser_ReviseUnitLaunchSilo_0004,
    BwWarActionReviser_ReviseUnitLaunchSilo_0005,
    BwWarActionReviser_ReviseUnitLaunchSilo_0006,
    BwWarActionReviser_ReviseUnitLaunchSilo_0007,
    BwWarActionReviser_ReviseUnitLaunchSilo_0008,
    BwWarActionReviser_ReviseUnitLaunchSilo_0009,

    BwWarActionReviser_ReviseUnitLoadCo_0000,
    BwWarActionReviser_ReviseUnitLoadCo_0001,
    BwWarActionReviser_ReviseUnitLoadCo_0002,
    BwWarActionReviser_ReviseUnitLoadCo_0003,
    BwWarActionReviser_ReviseUnitLoadCo_0004,
    BwWarActionReviser_ReviseUnitLoadCo_0005,
    BwWarActionReviser_ReviseUnitLoadCo_0006,
    BwWarActionReviser_ReviseUnitLoadCo_0007,
    BwWarActionReviser_ReviseUnitLoadCo_0008,
    BwWarActionReviser_ReviseUnitLoadCo_0009,

    BwWarActionReviser_ReviseUnitProduceUnit_0000,
    BwWarActionReviser_ReviseUnitProduceUnit_0001,
    BwWarActionReviser_ReviseUnitProduceUnit_0002,
    BwWarActionReviser_ReviseUnitProduceUnit_0003,
    BwWarActionReviser_ReviseUnitProduceUnit_0004,
    BwWarActionReviser_ReviseUnitProduceUnit_0005,
    BwWarActionReviser_ReviseUnitProduceUnit_0006,
    BwWarActionReviser_ReviseUnitProduceUnit_0007,
    BwWarActionReviser_ReviseUnitProduceUnit_0008,
    BwWarActionReviser_ReviseUnitProduceUnit_0009,

    BwWarActionReviser_ReviseUnitSupplyUnit_0000,
    BwWarActionReviser_ReviseUnitSupplyUnit_0001,
    BwWarActionReviser_ReviseUnitSupplyUnit_0002,
    BwWarActionReviser_ReviseUnitSupplyUnit_0003,
    BwWarActionReviser_ReviseUnitSupplyUnit_0004,
    BwWarActionReviser_ReviseUnitSupplyUnit_0005,
    BwWarActionReviser_ReviseUnitSupplyUnit_0006,
    BwWarActionReviser_ReviseUnitSupplyUnit_0007,
    BwWarActionReviser_ReviseUnitSupplyUnit_0008,
    BwWarActionReviser_ReviseUnitSupplyUnit_0009,

    BwWarActionReviser_ReviseUnitSurface_0000,
    BwWarActionReviser_ReviseUnitSurface_0001,
    BwWarActionReviser_ReviseUnitSurface_0002,
    BwWarActionReviser_ReviseUnitSurface_0003,
    BwWarActionReviser_ReviseUnitSurface_0004,
    BwWarActionReviser_ReviseUnitSurface_0005,
    BwWarActionReviser_ReviseUnitSurface_0006,
    BwWarActionReviser_ReviseUnitSurface_0007,
    BwWarActionReviser_ReviseUnitSurface_0008,
    BwWarActionReviser_ReviseUnitSurface_0009,

    BwWarActionReviser_ReviseUnitUseCoSkill_0000,
    BwWarActionReviser_ReviseUnitUseCoSkill_0001,
    BwWarActionReviser_ReviseUnitUseCoSkill_0002,
    BwWarActionReviser_ReviseUnitUseCoSkill_0003,
    BwWarActionReviser_ReviseUnitUseCoSkill_0004,
    BwWarActionReviser_ReviseUnitUseCoSkill_0005,
    BwWarActionReviser_ReviseUnitUseCoSkill_0006,
    BwWarActionReviser_ReviseUnitUseCoSkill_0007,
    BwWarActionReviser_ReviseUnitUseCoSkill_0008,
    BwWarActionReviser_ReviseUnitUseCoSkill_0009,

    BwWarActionReviser_ReviseUnitWait_0000,
    BwWarActionReviser_ReviseUnitWait_0001,
    BwWarActionReviser_ReviseUnitWait_0002,
    BwWarActionReviser_ReviseUnitWait_0003,
    BwWarActionReviser_ReviseUnitWait_0004,
    BwWarActionReviser_ReviseUnitWait_0005,
    BwWarActionReviser_ReviseUnitWait_0006,
    BwWarActionReviser_ReviseUnitWait_0007,
    BwWarActionReviser_ReviseUnitWait_0008,
    BwWarActionReviser_ReviseUnitWait_0009,

    BwWarActionReviser_ReviseUnknownAction_0000,
    BwWarActionReviser_ReviseUnknownAction_0001,
    BwWarActionReviser_ReviseUnknownAction_0002,
    BwWarActionReviser_ReviseUnknownAction_0003,
    BwWarActionReviser_ReviseUnknownAction_0004,
    BwWarActionReviser_ReviseUnknownAction_0005,
    BwWarActionReviser_ReviseUnknownAction_0006,
    BwWarActionReviser_ReviseUnknownAction_0007,
    BwWarActionReviser_ReviseUnknownAction_0008,
    BwWarActionReviser_ReviseUnknownAction_0009,

    BwWarActionExecutor_ExecuteAction_0000,
    BwWarActionExecutor_ExecuteAction_0001,
    BwWarActionExecutor_ExecuteAction_0002,
    BwWarActionExecutor_ExecuteAction_0003,
    BwWarActionExecutor_ExecuteAction_0004,
    BwWarActionExecutor_ExecuteAction_0005,
    BwWarActionExecutor_ExecuteAction_0006,
    BwWarActionExecutor_ExecuteAction_0007,
    BwWarActionExecutor_ExecuteAction_0008,
    BwWarActionExecutor_ExecuteAction_0009,

    BwWarActionExecutor_ExePlayerDeleteUnit_0000,
    BwWarActionExecutor_ExePlayerDeleteUnit_0001,
    BwWarActionExecutor_ExePlayerDeleteUnit_0002,
    BwWarActionExecutor_ExePlayerDeleteUnit_0003,
    BwWarActionExecutor_ExePlayerDeleteUnit_0004,
    BwWarActionExecutor_ExePlayerDeleteUnit_0005,
    BwWarActionExecutor_ExePlayerDeleteUnit_0006,
    BwWarActionExecutor_ExePlayerDeleteUnit_0007,
    BwWarActionExecutor_ExePlayerDeleteUnit_0008,
    BwWarActionExecutor_ExePlayerDeleteUnit_0009,

    BwWarActionExecutor_ExePlayerEndTurn_0000,
    BwWarActionExecutor_ExePlayerEndTurn_0001,
    BwWarActionExecutor_ExePlayerEndTurn_0002,
    BwWarActionExecutor_ExePlayerEndTurn_0003,
    BwWarActionExecutor_ExePlayerEndTurn_0004,
    BwWarActionExecutor_ExePlayerEndTurn_0005,
    BwWarActionExecutor_ExePlayerEndTurn_0006,
    BwWarActionExecutor_ExePlayerEndTurn_0007,
    BwWarActionExecutor_ExePlayerEndTurn_0008,
    BwWarActionExecutor_ExePlayerEndTurn_0009,

    BwWarActionExecutor_ExePlayerSurrender_0000,
    BwWarActionExecutor_ExePlayerSurrender_0001,
    BwWarActionExecutor_ExePlayerSurrender_0002,
    BwWarActionExecutor_ExePlayerSurrender_0003,
    BwWarActionExecutor_ExePlayerSurrender_0004,
    BwWarActionExecutor_ExePlayerSurrender_0005,
    BwWarActionExecutor_ExePlayerSurrender_0006,
    BwWarActionExecutor_ExePlayerSurrender_0007,
    BwWarActionExecutor_ExePlayerSurrender_0008,
    BwWarActionExecutor_ExePlayerSurrender_0009,

    BwWarActionExecutor_ExePlayerVoteForDraw_0000,
    BwWarActionExecutor_ExePlayerVoteForDraw_0001,
    BwWarActionExecutor_ExePlayerVoteForDraw_0002,
    BwWarActionExecutor_ExePlayerVoteForDraw_0003,
    BwWarActionExecutor_ExePlayerVoteForDraw_0004,
    BwWarActionExecutor_ExePlayerVoteForDraw_0005,
    BwWarActionExecutor_ExePlayerVoteForDraw_0006,
    BwWarActionExecutor_ExePlayerVoteForDraw_0007,
    BwWarActionExecutor_ExePlayerVoteForDraw_0008,
    BwWarActionExecutor_ExePlayerVoteForDraw_0009,

    BwWarActionExecutor_ExePlayerProduceUnit_0000,
    BwWarActionExecutor_ExePlayerProduceUnit_0001,
    BwWarActionExecutor_ExePlayerProduceUnit_0002,
    BwWarActionExecutor_ExePlayerProduceUnit_0003,
    BwWarActionExecutor_ExePlayerProduceUnit_0004,
    BwWarActionExecutor_ExePlayerProduceUnit_0005,
    BwWarActionExecutor_ExePlayerProduceUnit_0006,
    BwWarActionExecutor_ExePlayerProduceUnit_0007,
    BwWarActionExecutor_ExePlayerProduceUnit_0008,
    BwWarActionExecutor_ExePlayerProduceUnit_0009,
    BwWarActionExecutor_ExePlayerProduceUnit_0010,
    BwWarActionExecutor_ExePlayerProduceUnit_0011,
    BwWarActionExecutor_ExePlayerProduceUnit_0012,
    BwWarActionExecutor_ExePlayerProduceUnit_0013,
    BwWarActionExecutor_ExePlayerProduceUnit_0014,
    BwWarActionExecutor_ExePlayerProduceUnit_0015,
    BwWarActionExecutor_ExePlayerProduceUnit_0016,
    BwWarActionExecutor_ExePlayerProduceUnit_0017,
    BwWarActionExecutor_ExePlayerProduceUnit_0018,
    BwWarActionExecutor_ExePlayerProduceUnit_0019,

    BwWarActionExecutor_ExeSystemBeginTurn_0000,
    BwWarActionExecutor_ExeSystemBeginTurn_0001,
    BwWarActionExecutor_ExeSystemBeginTurn_0002,
    BwWarActionExecutor_ExeSystemBeginTurn_0003,
    BwWarActionExecutor_ExeSystemBeginTurn_0004,
    BwWarActionExecutor_ExeSystemBeginTurn_0005,
    BwWarActionExecutor_ExeSystemBeginTurn_0006,
    BwWarActionExecutor_ExeSystemBeginTurn_0007,
    BwWarActionExecutor_ExeSystemBeginTurn_0008,
    BwWarActionExecutor_ExeSystemBeginTurn_0009,

    BwWarActionExecutor_ExeSystemCallWarEvent_0000,
    BwWarActionExecutor_ExeSystemCallWarEvent_0001,
    BwWarActionExecutor_ExeSystemCallWarEvent_0002,
    BwWarActionExecutor_ExeSystemCallWarEvent_0003,
    BwWarActionExecutor_ExeSystemCallWarEvent_0004,
    BwWarActionExecutor_ExeSystemCallWarEvent_0005,
    BwWarActionExecutor_ExeSystemCallWarEvent_0006,
    BwWarActionExecutor_ExeSystemCallWarEvent_0007,
    BwWarActionExecutor_ExeSystemCallWarEvent_0008,
    BwWarActionExecutor_ExeSystemCallWarEvent_0009,

    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0000,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0001,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0002,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0003,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0004,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0005,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0006,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0007,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0008,
    BwWarActionExecutor_ExeSystemDestroyPlayerForce_0009,

    BwWarActionExecutor_ExeSystemEndWar_0000,
    BwWarActionExecutor_ExeSystemEndWar_0001,
    BwWarActionExecutor_ExeSystemEndWar_0002,
    BwWarActionExecutor_ExeSystemEndWar_0003,
    BwWarActionExecutor_ExeSystemEndWar_0004,
    BwWarActionExecutor_ExeSystemEndWar_0005,
    BwWarActionExecutor_ExeSystemEndWar_0006,
    BwWarActionExecutor_ExeSystemEndWar_0007,
    BwWarActionExecutor_ExeSystemEndWar_0008,
    BwWarActionExecutor_ExeSystemEndWar_0009,

    BwWarActionExecutor_ExeUnitAttackUnit_0000,
    BwWarActionExecutor_ExeUnitAttackUnit_0001,
    BwWarActionExecutor_ExeUnitAttackUnit_0002,
    BwWarActionExecutor_ExeUnitAttackUnit_0003,
    BwWarActionExecutor_ExeUnitAttackUnit_0004,
    BwWarActionExecutor_ExeUnitAttackUnit_0005,
    BwWarActionExecutor_ExeUnitAttackUnit_0006,
    BwWarActionExecutor_ExeUnitAttackUnit_0007,
    BwWarActionExecutor_ExeUnitAttackUnit_0008,
    BwWarActionExecutor_ExeUnitAttackUnit_0009,
    BwWarActionExecutor_ExeUnitAttackUnit_0010,
    BwWarActionExecutor_ExeUnitAttackUnit_0011,
    BwWarActionExecutor_ExeUnitAttackUnit_0012,
    BwWarActionExecutor_ExeUnitAttackUnit_0013,
    BwWarActionExecutor_ExeUnitAttackUnit_0014,
    BwWarActionExecutor_ExeUnitAttackUnit_0015,
    BwWarActionExecutor_ExeUnitAttackUnit_0016,
    BwWarActionExecutor_ExeUnitAttackUnit_0017,
    BwWarActionExecutor_ExeUnitAttackUnit_0018,
    BwWarActionExecutor_ExeUnitAttackUnit_0019,
    BwWarActionExecutor_ExeUnitAttackUnit_0020,
    BwWarActionExecutor_ExeUnitAttackUnit_0021,
    BwWarActionExecutor_ExeUnitAttackUnit_0022,
    BwWarActionExecutor_ExeUnitAttackUnit_0023,
    BwWarActionExecutor_ExeUnitAttackUnit_0024,
    BwWarActionExecutor_ExeUnitAttackUnit_0025,
    BwWarActionExecutor_ExeUnitAttackUnit_0026,
    BwWarActionExecutor_ExeUnitAttackUnit_0027,
    BwWarActionExecutor_ExeUnitAttackUnit_0028,
    BwWarActionExecutor_ExeUnitAttackUnit_0029,

    BwWarActionExecutor_ExeUnitAttackTile_0000,
    BwWarActionExecutor_ExeUnitAttackTile_0001,
    BwWarActionExecutor_ExeUnitAttackTile_0002,
    BwWarActionExecutor_ExeUnitAttackTile_0003,
    BwWarActionExecutor_ExeUnitAttackTile_0004,
    BwWarActionExecutor_ExeUnitAttackTile_0005,
    BwWarActionExecutor_ExeUnitAttackTile_0006,
    BwWarActionExecutor_ExeUnitAttackTile_0007,
    BwWarActionExecutor_ExeUnitAttackTile_0008,
    BwWarActionExecutor_ExeUnitAttackTile_0009,
    BwWarActionExecutor_ExeUnitAttackTile_0010,
    BwWarActionExecutor_ExeUnitAttackTile_0011,
    BwWarActionExecutor_ExeUnitAttackTile_0012,
    BwWarActionExecutor_ExeUnitAttackTile_0013,
    BwWarActionExecutor_ExeUnitAttackTile_0014,
    BwWarActionExecutor_ExeUnitAttackTile_0015,
    BwWarActionExecutor_ExeUnitAttackTile_0016,
    BwWarActionExecutor_ExeUnitAttackTile_0017,
    BwWarActionExecutor_ExeUnitAttackTile_0018,
    BwWarActionExecutor_ExeUnitAttackTile_0019,

    BwWarActionExecutor_ExeUnitBeLoaded_0000,
    BwWarActionExecutor_ExeUnitBeLoaded_0001,
    BwWarActionExecutor_ExeUnitBeLoaded_0002,
    BwWarActionExecutor_ExeUnitBeLoaded_0003,
    BwWarActionExecutor_ExeUnitBeLoaded_0004,
    BwWarActionExecutor_ExeUnitBeLoaded_0005,
    BwWarActionExecutor_ExeUnitBeLoaded_0006,
    BwWarActionExecutor_ExeUnitBeLoaded_0007,
    BwWarActionExecutor_ExeUnitBeLoaded_0008,
    BwWarActionExecutor_ExeUnitBeLoaded_0009,

    BwWarActionExecutor_ExeUnitBuildTile_0000,
    BwWarActionExecutor_ExeUnitBuildTile_0001,
    BwWarActionExecutor_ExeUnitBuildTile_0002,
    BwWarActionExecutor_ExeUnitBuildTile_0003,
    BwWarActionExecutor_ExeUnitBuildTile_0004,
    BwWarActionExecutor_ExeUnitBuildTile_0005,
    BwWarActionExecutor_ExeUnitBuildTile_0006,
    BwWarActionExecutor_ExeUnitBuildTile_0007,
    BwWarActionExecutor_ExeUnitBuildTile_0008,
    BwWarActionExecutor_ExeUnitBuildTile_0009,
    BwWarActionExecutor_ExeUnitBuildTile_0010,
    BwWarActionExecutor_ExeUnitBuildTile_0011,
    BwWarActionExecutor_ExeUnitBuildTile_0012,
    BwWarActionExecutor_ExeUnitBuildTile_0013,
    BwWarActionExecutor_ExeUnitBuildTile_0014,
    BwWarActionExecutor_ExeUnitBuildTile_0015,
    BwWarActionExecutor_ExeUnitBuildTile_0016,
    BwWarActionExecutor_ExeUnitBuildTile_0017,
    BwWarActionExecutor_ExeUnitBuildTile_0018,
    BwWarActionExecutor_ExeUnitBuildTile_0019,

    BwWarActionExecutor_ExeUnitCaptureTile_0000,
    BwWarActionExecutor_ExeUnitCaptureTile_0001,
    BwWarActionExecutor_ExeUnitCaptureTile_0002,
    BwWarActionExecutor_ExeUnitCaptureTile_0003,
    BwWarActionExecutor_ExeUnitCaptureTile_0004,
    BwWarActionExecutor_ExeUnitCaptureTile_0005,
    BwWarActionExecutor_ExeUnitCaptureTile_0006,
    BwWarActionExecutor_ExeUnitCaptureTile_0007,
    BwWarActionExecutor_ExeUnitCaptureTile_0008,
    BwWarActionExecutor_ExeUnitCaptureTile_0009,
    BwWarActionExecutor_ExeUnitCaptureTile_0010,
    BwWarActionExecutor_ExeUnitCaptureTile_0011,
    BwWarActionExecutor_ExeUnitCaptureTile_0012,
    BwWarActionExecutor_ExeUnitCaptureTile_0013,
    BwWarActionExecutor_ExeUnitCaptureTile_0014,
    BwWarActionExecutor_ExeUnitCaptureTile_0015,
    BwWarActionExecutor_ExeUnitCaptureTile_0016,
    BwWarActionExecutor_ExeUnitCaptureTile_0017,
    BwWarActionExecutor_ExeUnitCaptureTile_0018,
    BwWarActionExecutor_ExeUnitCaptureTile_0019,

    BwWarActionExecutor_ExeUnitDive_0000,
    BwWarActionExecutor_ExeUnitDive_0001,
    BwWarActionExecutor_ExeUnitDive_0002,
    BwWarActionExecutor_ExeUnitDive_0003,
    BwWarActionExecutor_ExeUnitDive_0004,
    BwWarActionExecutor_ExeUnitDive_0005,
    BwWarActionExecutor_ExeUnitDive_0006,
    BwWarActionExecutor_ExeUnitDive_0007,
    BwWarActionExecutor_ExeUnitDive_0008,
    BwWarActionExecutor_ExeUnitDive_0009,

    BwWarActionExecutor_ExeUnitDropUnit_0000,
    BwWarActionExecutor_ExeUnitDropUnit_0001,
    BwWarActionExecutor_ExeUnitDropUnit_0002,
    BwWarActionExecutor_ExeUnitDropUnit_0003,
    BwWarActionExecutor_ExeUnitDropUnit_0004,
    BwWarActionExecutor_ExeUnitDropUnit_0005,
    BwWarActionExecutor_ExeUnitDropUnit_0006,
    BwWarActionExecutor_ExeUnitDropUnit_0007,
    BwWarActionExecutor_ExeUnitDropUnit_0008,
    BwWarActionExecutor_ExeUnitDropUnit_0009,

    BwWarActionExecutor_ExeUnitJoinUnit_0000,
    BwWarActionExecutor_ExeUnitJoinUnit_0001,
    BwWarActionExecutor_ExeUnitJoinUnit_0002,
    BwWarActionExecutor_ExeUnitJoinUnit_0003,
    BwWarActionExecutor_ExeUnitJoinUnit_0004,
    BwWarActionExecutor_ExeUnitJoinUnit_0005,
    BwWarActionExecutor_ExeUnitJoinUnit_0006,
    BwWarActionExecutor_ExeUnitJoinUnit_0007,
    BwWarActionExecutor_ExeUnitJoinUnit_0008,
    BwWarActionExecutor_ExeUnitJoinUnit_0009,
    BwWarActionExecutor_ExeUnitJoinUnit_0010,
    BwWarActionExecutor_ExeUnitJoinUnit_0011,
    BwWarActionExecutor_ExeUnitJoinUnit_0012,
    BwWarActionExecutor_ExeUnitJoinUnit_0013,
    BwWarActionExecutor_ExeUnitJoinUnit_0014,
    BwWarActionExecutor_ExeUnitJoinUnit_0015,
    BwWarActionExecutor_ExeUnitJoinUnit_0016,
    BwWarActionExecutor_ExeUnitJoinUnit_0017,
    BwWarActionExecutor_ExeUnitJoinUnit_0018,
    BwWarActionExecutor_ExeUnitJoinUnit_0019,
    BwWarActionExecutor_ExeUnitJoinUnit_0020,
    BwWarActionExecutor_ExeUnitJoinUnit_0021,
    BwWarActionExecutor_ExeUnitJoinUnit_0022,
    BwWarActionExecutor_ExeUnitJoinUnit_0023,
    BwWarActionExecutor_ExeUnitJoinUnit_0024,
    BwWarActionExecutor_ExeUnitJoinUnit_0025,
    BwWarActionExecutor_ExeUnitJoinUnit_0026,
    BwWarActionExecutor_ExeUnitJoinUnit_0027,
    BwWarActionExecutor_ExeUnitJoinUnit_0028,
    BwWarActionExecutor_ExeUnitJoinUnit_0029,

    BwWarActionExecutor_ExeUnitLaunchFlare_0000,
    BwWarActionExecutor_ExeUnitLaunchFlare_0001,
    BwWarActionExecutor_ExeUnitLaunchFlare_0002,
    BwWarActionExecutor_ExeUnitLaunchFlare_0003,
    BwWarActionExecutor_ExeUnitLaunchFlare_0004,
    BwWarActionExecutor_ExeUnitLaunchFlare_0005,
    BwWarActionExecutor_ExeUnitLaunchFlare_0006,
    BwWarActionExecutor_ExeUnitLaunchFlare_0007,
    BwWarActionExecutor_ExeUnitLaunchFlare_0008,
    BwWarActionExecutor_ExeUnitLaunchFlare_0009,

    BwWarActionExecutor_ExeUnitLaunchSilo_0000,
    BwWarActionExecutor_ExeUnitLaunchSilo_0001,
    BwWarActionExecutor_ExeUnitLaunchSilo_0002,
    BwWarActionExecutor_ExeUnitLaunchSilo_0003,
    BwWarActionExecutor_ExeUnitLaunchSilo_0004,
    BwWarActionExecutor_ExeUnitLaunchSilo_0005,
    BwWarActionExecutor_ExeUnitLaunchSilo_0006,
    BwWarActionExecutor_ExeUnitLaunchSilo_0007,
    BwWarActionExecutor_ExeUnitLaunchSilo_0008,
    BwWarActionExecutor_ExeUnitLaunchSilo_0009,

    BwWarActionExecutor_ExeUnitLoadCo_0000,
    BwWarActionExecutor_ExeUnitLoadCo_0001,
    BwWarActionExecutor_ExeUnitLoadCo_0002,
    BwWarActionExecutor_ExeUnitLoadCo_0003,
    BwWarActionExecutor_ExeUnitLoadCo_0004,
    BwWarActionExecutor_ExeUnitLoadCo_0005,
    BwWarActionExecutor_ExeUnitLoadCo_0006,
    BwWarActionExecutor_ExeUnitLoadCo_0007,
    BwWarActionExecutor_ExeUnitLoadCo_0008,
    BwWarActionExecutor_ExeUnitLoadCo_0009,
    BwWarActionExecutor_ExeUnitLoadCo_0010,
    BwWarActionExecutor_ExeUnitLoadCo_0011,
    BwWarActionExecutor_ExeUnitLoadCo_0012,
    BwWarActionExecutor_ExeUnitLoadCo_0013,
    BwWarActionExecutor_ExeUnitLoadCo_0014,
    BwWarActionExecutor_ExeUnitLoadCo_0015,
    BwWarActionExecutor_ExeUnitLoadCo_0016,
    BwWarActionExecutor_ExeUnitLoadCo_0017,
    BwWarActionExecutor_ExeUnitLoadCo_0018,
    BwWarActionExecutor_ExeUnitLoadCo_0019,

    BwWarActionExecutor_ExeUnitProduceUnit_0000,
    BwWarActionExecutor_ExeUnitProduceUnit_0001,
    BwWarActionExecutor_ExeUnitProduceUnit_0002,
    BwWarActionExecutor_ExeUnitProduceUnit_0003,
    BwWarActionExecutor_ExeUnitProduceUnit_0004,
    BwWarActionExecutor_ExeUnitProduceUnit_0005,
    BwWarActionExecutor_ExeUnitProduceUnit_0006,
    BwWarActionExecutor_ExeUnitProduceUnit_0007,
    BwWarActionExecutor_ExeUnitProduceUnit_0008,
    BwWarActionExecutor_ExeUnitProduceUnit_0009,

    BwWarActionExecutor_ExeUnitSupplyUnit_0000,
    BwWarActionExecutor_ExeUnitSupplyUnit_0001,
    BwWarActionExecutor_ExeUnitSupplyUnit_0002,
    BwWarActionExecutor_ExeUnitSupplyUnit_0003,
    BwWarActionExecutor_ExeUnitSupplyUnit_0004,
    BwWarActionExecutor_ExeUnitSupplyUnit_0005,
    BwWarActionExecutor_ExeUnitSupplyUnit_0006,
    BwWarActionExecutor_ExeUnitSupplyUnit_0007,
    BwWarActionExecutor_ExeUnitSupplyUnit_0008,
    BwWarActionExecutor_ExeUnitSupplyUnit_0009,

    BwWarActionExecutor_ExeUnitSurface_0000,
    BwWarActionExecutor_ExeUnitSurface_0001,
    BwWarActionExecutor_ExeUnitSurface_0002,
    BwWarActionExecutor_ExeUnitSurface_0003,
    BwWarActionExecutor_ExeUnitSurface_0004,
    BwWarActionExecutor_ExeUnitSurface_0005,
    BwWarActionExecutor_ExeUnitSurface_0006,
    BwWarActionExecutor_ExeUnitSurface_0007,
    BwWarActionExecutor_ExeUnitSurface_0008,
    BwWarActionExecutor_ExeUnitSurface_0009,

    BwWarActionExecutor_ExeUnitUseCoSkill_0000,
    BwWarActionExecutor_ExeUnitUseCoSkill_0001,
    BwWarActionExecutor_ExeUnitUseCoSkill_0002,
    BwWarActionExecutor_ExeUnitUseCoSkill_0003,
    BwWarActionExecutor_ExeUnitUseCoSkill_0004,
    BwWarActionExecutor_ExeUnitUseCoSkill_0005,
    BwWarActionExecutor_ExeUnitUseCoSkill_0006,
    BwWarActionExecutor_ExeUnitUseCoSkill_0007,
    BwWarActionExecutor_ExeUnitUseCoSkill_0008,
    BwWarActionExecutor_ExeUnitUseCoSkill_0009,
    BwWarActionExecutor_ExeUnitUseCoSkill_0010,
    BwWarActionExecutor_ExeUnitUseCoSkill_0011,
    BwWarActionExecutor_ExeUnitUseCoSkill_0012,
    BwWarActionExecutor_ExeUnitUseCoSkill_0013,
    BwWarActionExecutor_ExeUnitUseCoSkill_0014,
    BwWarActionExecutor_ExeUnitUseCoSkill_0015,
    BwWarActionExecutor_ExeUnitUseCoSkill_0016,
    BwWarActionExecutor_ExeUnitUseCoSkill_0017,
    BwWarActionExecutor_ExeUnitUseCoSkill_0018,
    BwWarActionExecutor_ExeUnitUseCoSkill_0019,

    BwWarActionExecutor_ExeUnitWait_0000,
    BwWarActionExecutor_ExeUnitWait_0001,
    BwWarActionExecutor_ExeUnitWait_0002,
    BwWarActionExecutor_ExeUnitWait_0003,
    BwWarActionExecutor_ExeUnitWait_0004,
    BwWarActionExecutor_ExeUnitWait_0005,
    BwWarActionExecutor_ExeUnitWait_0006,
    BwWarActionExecutor_ExeUnitWait_0007,
    BwWarActionExecutor_ExeUnitWait_0008,
    BwWarActionExecutor_ExeUnitWait_0009,

    BwWarActionExecutor_ExeUnknownAction_0000,
    BwWarActionExecutor_ExeUnknownAction_0001,
    BwWarActionExecutor_ExeUnknownAction_0002,
    BwWarActionExecutor_ExeUnknownAction_0003,
    BwWarActionExecutor_ExeUnknownAction_0004,
    BwWarActionExecutor_ExeUnknownAction_0005,
    BwWarActionExecutor_ExeUnknownAction_0006,
    BwWarActionExecutor_ExeUnknownAction_0007,
    BwWarActionExecutor_ExeUnknownAction_0008,
    BwWarActionExecutor_ExeUnknownAction_0009,

    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0000,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0001,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0002,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0003,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0004,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0005,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0006,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0007,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0008,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackTile_0009,

    BwWarActionExecutor_HandleDestructionForTile_0000,
    BwWarActionExecutor_HandleDestructionForTile_0001,
    BwWarActionExecutor_HandleDestructionForTile_0002,
    BwWarActionExecutor_HandleDestructionForTile_0003,
    BwWarActionExecutor_HandleDestructionForTile_0004,
    BwWarActionExecutor_HandleDestructionForTile_0005,
    BwWarActionExecutor_HandleDestructionForTile_0006,
    BwWarActionExecutor_HandleDestructionForTile_0007,
    BwWarActionExecutor_HandleDestructionForTile_0008,
    BwWarActionExecutor_HandleDestructionForTile_0009,

    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0000,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0001,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0002,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0003,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0004,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0005,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0006,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0007,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0008,
    BwWarActionExecutor_HandlePrimaryWeaponForUnitAttackUnit_0009,

    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0000,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0001,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0002,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0003,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0004,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0005,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0006,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0007,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0008,
    BwWarActionExecutor_HandlePromotionForUnitAttackUnit_0009,

    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0000,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0001,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0002,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0003,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0004,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0005,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0006,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0007,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0008,
    BwWarActionExecutor_HandleEnergyForUnitAttackUnit_0009,

    BwWarActionExecutor_HandleDestructionForUnit_0000,
    BwWarActionExecutor_HandleDestructionForUnit_0001,
    BwWarActionExecutor_HandleDestructionForUnit_0002,
    BwWarActionExecutor_HandleDestructionForUnit_0003,
    BwWarActionExecutor_HandleDestructionForUnit_0004,
    BwWarActionExecutor_HandleDestructionForUnit_0005,
    BwWarActionExecutor_HandleDestructionForUnit_0006,
    BwWarActionExecutor_HandleDestructionForUnit_0007,
    BwWarActionExecutor_HandleDestructionForUnit_0008,
    BwWarActionExecutor_HandleDestructionForUnit_0009,

    VisibilityHelpers_GetDiscoveredUnitsByPath_0000,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0001,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0002,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0003,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0004,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0005,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0006,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0007,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0008,
    VisibilityHelpers_GetDiscoveredUnitsByPath_0009,

    DamageCalculator_GetBattleDamage_0000,
    DamageCalculator_GetBattleDamage_0001,
    DamageCalculator_GetBattleDamage_0002,
    DamageCalculator_GetBattleDamage_0003,
    DamageCalculator_GetBattleDamage_0004,
    DamageCalculator_GetBattleDamage_0005,
    DamageCalculator_GetBattleDamage_0006,
    DamageCalculator_GetBattleDamage_0007,
    DamageCalculator_GetBattleDamage_0008,
    DamageCalculator_GetBattleDamage_0009,
    DamageCalculator_GetBattleDamage_0010,
    DamageCalculator_GetBattleDamage_0011,
    DamageCalculator_GetBattleDamage_0012,
    DamageCalculator_GetBattleDamage_0013,
    DamageCalculator_GetBattleDamage_0014,
    DamageCalculator_GetBattleDamage_0015,
    DamageCalculator_GetBattleDamage_0016,
    DamageCalculator_GetBattleDamage_0017,
    DamageCalculator_GetBattleDamage_0018,
    DamageCalculator_GetBattleDamage_0019,

    UnitDataValidation0000,
    UnitDataValidation0001,
    UnitDataValidation0002,
    UnitDataValidation0003,
    UnitDataValidation0004,
    UnitDataValidation0005,
    UnitDataValidation0006,
    UnitDataValidation0007,
    UnitDataValidation0008,
    UnitDataValidation0009,
    UnitDataValidation0010,
    UnitDataValidation0011,
    UnitDataValidation0012,
    UnitDataValidation0013,
    UnitDataValidation0014,
    UnitDataValidation0015,
    UnitDataValidation0016,

    MapRawDataValidation0000,
    MapRawDataValidation0001,
    MapRawDataValidation0002,
    MapRawDataValidation0003,
    MapRawDataValidation0004,
    MapRawDataValidation0005,
    MapRawDataValidation0006,
    MapRawDataValidation0007,
    MapRawDataValidation0008,

    SrwValidator_DoValidate_0000,
    SrwValidator_DoValidate_0001,
    SrwValidator_DoValidate_0002,
    SrwValidator_DoValidate_0003,
    SrwValidator_DoValidate_0004,
    SrwValidator_DoValidate_0005,
    SrwValidator_DoValidate_0006,
    SrwValidator_DoValidate_0007,
    SrwValidator_DoValidate_0008,
    SrwValidator_DoValidate_0009,
    SrwValidator_DoValidate_0010,
    SrwValidator_DoValidate_0011,
    SrwValidator_DoValidate_0012,
    SrwValidator_DoValidate_0013,
    SrwValidator_DoValidate_0014,
    SrwValidator_DoValidate_0015,
    SrwValidator_DoValidate_0016,
    SrwValidator_DoValidate_0017,
    SrwValidator_DoValidate_0018,
    SrwValidator_DoValidate_0019,
    SrwValidator_DoValidate_0020,
    SrwValidator_DoValidate_0021,
    SrwValidator_DoValidate_0022,
    SrwValidator_DoValidate_0023,
    SrwValidator_DoValidate_0024,
    SrwValidator_DoValidate_0025,
    SrwValidator_DoValidate_0026,
    SrwValidator_DoValidate_0027,
    SrwValidator_DoValidate_0028,
    SrwValidator_DoValidate_0029,

    SrwValidator_GetNextAutoOrRobotAction_0000,
    SrwValidator_GetNextAutoOrRobotAction_0001,
    SrwValidator_GetNextAutoOrRobotAction_0002,
    SrwValidator_GetNextAutoOrRobotAction_0003,
    SrwValidator_GetNextAutoOrRobotAction_0004,
    SrwValidator_GetNextAutoOrRobotAction_0005,
    SrwValidator_GetNextAutoOrRobotAction_0006,
    SrwValidator_GetNextAutoOrRobotAction_0007,
    SrwValidator_GetNextAutoOrRobotAction_0008,
    SrwValidator_GetNextAutoOrRobotAction_0009,

    SpwRobot_GetCommonParams_0000,
    SpwRobot_GetCommonParams_0001,
    SpwRobot_GetCommonParams_0002,
    SpwRobot_GetCommonParams_0003,
    SpwRobot_GetCommonParams_0004,
    SpwRobot_GetCommonParams_0005,
    SpwRobot_GetCommonParams_0006,
    SpwRobot_GetCommonParams_0007,
    SpwRobot_GetCommonParams_0008,
    SpwRobot_GetCommonParams_0009,

    SpwRobot_GetUnitValues_0000,
    SpwRobot_GetUnitValues_0001,
    SpwRobot_GetUnitValues_0002,
    SpwRobot_GetUnitValues_0003,
    SpwRobot_GetUnitValues_0004,
    SpwRobot_GetUnitValues_0005,
    SpwRobot_GetUnitValues_0006,
    SpwRobot_GetUnitValues_0007,
    SpwRobot_GetUnitValues_0008,
    SpwRobot_GetUnitValues_0009,

    SpwRobot_GetUnitValueRatio_0000,
    SpwRobot_GetUnitValueRatio_0001,
    SpwRobot_GetUnitValueRatio_0002,
    SpwRobot_GetUnitValueRatio_0003,
    SpwRobot_GetUnitValueRatio_0004,
    SpwRobot_GetUnitValueRatio_0005,
    SpwRobot_GetUnitValueRatio_0006,
    SpwRobot_GetUnitValueRatio_0007,
    SpwRobot_GetUnitValueRatio_0008,
    SpwRobot_GetUnitValueRatio_0009,

    SpwRobot_CheckCanUnitWaitOnGrid_0000,
    SpwRobot_CheckCanUnitWaitOnGrid_0001,
    SpwRobot_CheckCanUnitWaitOnGrid_0002,
    SpwRobot_CheckCanUnitWaitOnGrid_0003,
    SpwRobot_CheckCanUnitWaitOnGrid_0004,
    SpwRobot_CheckCanUnitWaitOnGrid_0005,
    SpwRobot_CheckCanUnitWaitOnGrid_0006,
    SpwRobot_CheckCanUnitWaitOnGrid_0007,
    SpwRobot_CheckCanUnitWaitOnGrid_0008,
    SpwRobot_CheckCanUnitWaitOnGrid_0009,

    SpwRobot_GetReachableArea_0000,
    SpwRobot_GetReachableArea_0001,
    SpwRobot_GetReachableArea_0002,
    SpwRobot_GetReachableArea_0003,
    SpwRobot_GetReachableArea_0004,
    SpwRobot_GetReachableArea_0005,
    SpwRobot_GetReachableArea_0006,
    SpwRobot_GetReachableArea_0007,
    SpwRobot_GetReachableArea_0008,
    SpwRobot_GetReachableArea_0009,

    SpwRobot_GetBestScoreAndActionForUnitAndPath_0000,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0001,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0002,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0003,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0004,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0005,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0006,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0007,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0008,
    SpwRobot_GetBestScoreAndActionForUnitAndPath_0009,

    SpwRobot_GetGlobalOffenseBonuses_0000,
    SpwRobot_GetGlobalOffenseBonuses_0001,
    SpwRobot_GetGlobalOffenseBonuses_0002,
    SpwRobot_GetGlobalOffenseBonuses_0003,
    SpwRobot_GetGlobalOffenseBonuses_0004,
    SpwRobot_GetGlobalOffenseBonuses_0005,
    SpwRobot_GetGlobalOffenseBonuses_0006,
    SpwRobot_GetGlobalOffenseBonuses_0007,
    SpwRobot_GetGlobalOffenseBonuses_0008,
    SpwRobot_GetGlobalOffenseBonuses_0009,

    SpwRobot_GetGlobalDefenseBonuses_0000,
    SpwRobot_GetGlobalDefenseBonuses_0001,
    SpwRobot_GetGlobalDefenseBonuses_0002,
    SpwRobot_GetGlobalDefenseBonuses_0003,
    SpwRobot_GetGlobalDefenseBonuses_0004,
    SpwRobot_GetGlobalDefenseBonuses_0005,
    SpwRobot_GetGlobalDefenseBonuses_0006,
    SpwRobot_GetGlobalDefenseBonuses_0007,
    SpwRobot_GetGlobalDefenseBonuses_0008,
    SpwRobot_GetGlobalDefenseBonuses_0009,

    SpwRobot_CreateDamageMap_0000,
    SpwRobot_CreateDamageMap_0001,
    SpwRobot_CreateDamageMap_0002,
    SpwRobot_CreateDamageMap_0003,
    SpwRobot_CreateDamageMap_0004,
    SpwRobot_CreateDamageMap_0005,
    SpwRobot_CreateDamageMap_0006,
    SpwRobot_CreateDamageMap_0007,
    SpwRobot_CreateDamageMap_0008,
    SpwRobot_CreateDamageMap_0009,

    SpwRobot_GetAttackInfo_0000,
    SpwRobot_GetAttackInfo_0001,
    SpwRobot_GetAttackInfo_0002,
    SpwRobot_GetAttackInfo_0003,
    SpwRobot_GetAttackInfo_0004,
    SpwRobot_GetAttackInfo_0005,
    SpwRobot_GetAttackInfo_0006,
    SpwRobot_GetAttackInfo_0007,
    SpwRobot_GetAttackInfo_0008,
    SpwRobot_GetAttackInfo_0009,

    SpwRobot_GetLuckValue_0000,
    SpwRobot_GetLuckValue_0001,
    SpwRobot_GetLuckValue_0002,
    SpwRobot_GetLuckValue_0003,
    SpwRobot_GetLuckValue_0004,
    SpwRobot_GetLuckValue_0005,
    SpwRobot_GetLuckValue_0006,
    SpwRobot_GetLuckValue_0007,
    SpwRobot_GetLuckValue_0008,
    SpwRobot_GetLuckValue_0009,

    SpwRobot_GetScoreForThreat_0000,
    SpwRobot_GetScoreForThreat_0001,
    SpwRobot_GetScoreForThreat_0002,
    SpwRobot_GetScoreForThreat_0003,
    SpwRobot_GetScoreForThreat_0004,
    SpwRobot_GetScoreForThreat_0005,
    SpwRobot_GetScoreForThreat_0006,
    SpwRobot_GetScoreForThreat_0007,
    SpwRobot_GetScoreForThreat_0008,
    SpwRobot_GetScoreForThreat_0009,

    SpwRobot_GetScoreForDistanceToCapturableBuildings_0000,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0001,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0002,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0003,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0004,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0005,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0006,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0007,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0008,
    SpwRobot_GetScoreForDistanceToCapturableBuildings_0009,

    SpwRobot_GetScoreForDistanceToOtherUnits_0000,
    SpwRobot_GetScoreForDistanceToOtherUnits_0001,
    SpwRobot_GetScoreForDistanceToOtherUnits_0002,
    SpwRobot_GetScoreForDistanceToOtherUnits_0003,
    SpwRobot_GetScoreForDistanceToOtherUnits_0004,
    SpwRobot_GetScoreForDistanceToOtherUnits_0005,
    SpwRobot_GetScoreForDistanceToOtherUnits_0006,
    SpwRobot_GetScoreForDistanceToOtherUnits_0007,
    SpwRobot_GetScoreForDistanceToOtherUnits_0008,
    SpwRobot_GetScoreForDistanceToOtherUnits_0009,

    SpwRobot_GetScoreForPosition_0000,
    SpwRobot_GetScoreForPosition_0001,
    SpwRobot_GetScoreForPosition_0002,
    SpwRobot_GetScoreForPosition_0003,
    SpwRobot_GetScoreForPosition_0004,
    SpwRobot_GetScoreForPosition_0005,
    SpwRobot_GetScoreForPosition_0006,
    SpwRobot_GetScoreForPosition_0007,
    SpwRobot_GetScoreForPosition_0008,
    SpwRobot_GetScoreForPosition_0009,

    SpwRobot_GetScoreForMovePath_0000,
    SpwRobot_GetScoreForMovePath_0001,
    SpwRobot_GetScoreForMovePath_0002,
    SpwRobot_GetScoreForMovePath_0003,
    SpwRobot_GetScoreForMovePath_0004,
    SpwRobot_GetScoreForMovePath_0005,
    SpwRobot_GetScoreForMovePath_0006,
    SpwRobot_GetScoreForMovePath_0007,
    SpwRobot_GetScoreForMovePath_0008,
    SpwRobot_GetScoreForMovePath_0009,

    SpwRobot_GetScoreForActionUnitBeLoaded_0000,
    SpwRobot_GetScoreForActionUnitBeLoaded_0001,
    SpwRobot_GetScoreForActionUnitBeLoaded_0002,
    SpwRobot_GetScoreForActionUnitBeLoaded_0003,
    SpwRobot_GetScoreForActionUnitBeLoaded_0004,
    SpwRobot_GetScoreForActionUnitBeLoaded_0005,
    SpwRobot_GetScoreForActionUnitBeLoaded_0006,
    SpwRobot_GetScoreForActionUnitBeLoaded_0007,
    SpwRobot_GetScoreForActionUnitBeLoaded_0008,
    SpwRobot_GetScoreForActionUnitBeLoaded_0009,

    SpwRobot_GetScoreForActionUnitJoin_0000,
    SpwRobot_GetScoreForActionUnitJoin_0001,
    SpwRobot_GetScoreForActionUnitJoin_0002,
    SpwRobot_GetScoreForActionUnitJoin_0003,
    SpwRobot_GetScoreForActionUnitJoin_0004,
    SpwRobot_GetScoreForActionUnitJoin_0005,
    SpwRobot_GetScoreForActionUnitJoin_0006,
    SpwRobot_GetScoreForActionUnitJoin_0007,
    SpwRobot_GetScoreForActionUnitJoin_0008,
    SpwRobot_GetScoreForActionUnitJoin_0009,

    SpwRobot_GetScoreForActionUnitAttack_0000,
    SpwRobot_GetScoreForActionUnitAttack_0001,
    SpwRobot_GetScoreForActionUnitAttack_0002,
    SpwRobot_GetScoreForActionUnitAttack_0003,
    SpwRobot_GetScoreForActionUnitAttack_0004,
    SpwRobot_GetScoreForActionUnitAttack_0005,
    SpwRobot_GetScoreForActionUnitAttack_0006,
    SpwRobot_GetScoreForActionUnitAttack_0007,
    SpwRobot_GetScoreForActionUnitAttack_0008,
    SpwRobot_GetScoreForActionUnitAttack_0009,
    SpwRobot_GetScoreForActionUnitAttack_0010,
    SpwRobot_GetScoreForActionUnitAttack_0011,
    SpwRobot_GetScoreForActionUnitAttack_0012,
    SpwRobot_GetScoreForActionUnitAttack_0013,
    SpwRobot_GetScoreForActionUnitAttack_0014,
    SpwRobot_GetScoreForActionUnitAttack_0015,
    SpwRobot_GetScoreForActionUnitAttack_0016,
    SpwRobot_GetScoreForActionUnitAttack_0017,
    SpwRobot_GetScoreForActionUnitAttack_0018,
    SpwRobot_GetScoreForActionUnitAttack_0019,
    SpwRobot_GetScoreForActionUnitAttack_0020,
    SpwRobot_GetScoreForActionUnitAttack_0021,
    SpwRobot_GetScoreForActionUnitAttack_0022,
    SpwRobot_GetScoreForActionUnitAttack_0023,
    SpwRobot_GetScoreForActionUnitAttack_0024,
    SpwRobot_GetScoreForActionUnitAttack_0025,
    SpwRobot_GetScoreForActionUnitAttack_0026,
    SpwRobot_GetScoreForActionUnitAttack_0027,
    SpwRobot_GetScoreForActionUnitAttack_0028,
    SpwRobot_GetScoreForActionUnitAttack_0029,

    SpwRobot_GetScoreForActionUnitCaptureTile_0000,
    SpwRobot_GetScoreForActionUnitCaptureTile_0001,
    SpwRobot_GetScoreForActionUnitCaptureTile_0002,
    SpwRobot_GetScoreForActionUnitCaptureTile_0003,
    SpwRobot_GetScoreForActionUnitCaptureTile_0004,
    SpwRobot_GetScoreForActionUnitCaptureTile_0005,
    SpwRobot_GetScoreForActionUnitCaptureTile_0006,
    SpwRobot_GetScoreForActionUnitCaptureTile_0007,
    SpwRobot_GetScoreForActionUnitCaptureTile_0008,
    SpwRobot_GetScoreForActionUnitCaptureTile_0009,

    SpwRobot_GetScoreForActionUnitDive_0000,
    SpwRobot_GetScoreForActionUnitDive_0001,
    SpwRobot_GetScoreForActionUnitDive_0002,
    SpwRobot_GetScoreForActionUnitDive_0003,
    SpwRobot_GetScoreForActionUnitDive_0004,
    SpwRobot_GetScoreForActionUnitDive_0005,
    SpwRobot_GetScoreForActionUnitDive_0006,
    SpwRobot_GetScoreForActionUnitDive_0007,
    SpwRobot_GetScoreForActionUnitDive_0008,
    SpwRobot_GetScoreForActionUnitDive_0009,

    SpwRobot_GetScoreForUnitLaunchFlare_0000,
    SpwRobot_GetScoreForUnitLaunchFlare_0001,
    SpwRobot_GetScoreForUnitLaunchFlare_0002,
    SpwRobot_GetScoreForUnitLaunchFlare_0003,
    SpwRobot_GetScoreForUnitLaunchFlare_0004,
    SpwRobot_GetScoreForUnitLaunchFlare_0005,
    SpwRobot_GetScoreForUnitLaunchFlare_0006,
    SpwRobot_GetScoreForUnitLaunchFlare_0007,
    SpwRobot_GetScoreForUnitLaunchFlare_0008,
    SpwRobot_GetScoreForUnitLaunchFlare_0009,

    SpwRobot_GetScoreForActionUnitSurface_0000,
    SpwRobot_GetScoreForActionUnitSurface_0001,
    SpwRobot_GetScoreForActionUnitSurface_0002,
    SpwRobot_GetScoreForActionUnitSurface_0003,
    SpwRobot_GetScoreForActionUnitSurface_0004,
    SpwRobot_GetScoreForActionUnitSurface_0005,
    SpwRobot_GetScoreForActionUnitSurface_0006,
    SpwRobot_GetScoreForActionUnitSurface_0007,
    SpwRobot_GetScoreForActionUnitSurface_0008,
    SpwRobot_GetScoreForActionUnitSurface_0009,

    SpwRobot_GetScoreForActionPlayerProduceUnit_0000,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0001,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0002,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0003,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0004,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0005,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0006,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0007,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0008,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0009,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0010,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0011,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0012,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0013,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0014,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0015,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0016,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0017,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0018,
    SpwRobot_GetScoreForActionPlayerProduceUnit_0019,

    SpwRobot_GetScoreAndActionUnitBeLoaded_0000,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0001,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0002,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0003,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0004,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0005,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0006,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0007,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0008,
    SpwRobot_GetScoreAndActionUnitBeLoaded_0009,

    SpwRobot_GetScoreAndActionUnitJoin_0000,
    SpwRobot_GetScoreAndActionUnitJoin_0001,
    SpwRobot_GetScoreAndActionUnitJoin_0002,
    SpwRobot_GetScoreAndActionUnitJoin_0003,
    SpwRobot_GetScoreAndActionUnitJoin_0004,
    SpwRobot_GetScoreAndActionUnitJoin_0005,
    SpwRobot_GetScoreAndActionUnitJoin_0006,
    SpwRobot_GetScoreAndActionUnitJoin_0007,
    SpwRobot_GetScoreAndActionUnitJoin_0008,
    SpwRobot_GetScoreAndActionUnitJoin_0009,

    SpwRobot_GetScoreAndActionUnitAttack_0000,
    SpwRobot_GetScoreAndActionUnitAttack_0001,
    SpwRobot_GetScoreAndActionUnitAttack_0002,
    SpwRobot_GetScoreAndActionUnitAttack_0003,
    SpwRobot_GetScoreAndActionUnitAttack_0004,
    SpwRobot_GetScoreAndActionUnitAttack_0005,
    SpwRobot_GetScoreAndActionUnitAttack_0006,
    SpwRobot_GetScoreAndActionUnitAttack_0007,
    SpwRobot_GetScoreAndActionUnitAttack_0008,
    SpwRobot_GetScoreAndActionUnitAttack_0009,

    SpwRobot_GetScoreAndActionUnitCaptureTile_0000,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0001,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0002,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0003,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0004,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0005,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0006,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0007,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0008,
    SpwRobot_GetScoreAndActionUnitCaptureTile_0009,

    SpwRobot_GetScoreAndActionUnitLaunchSilo_0000,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0001,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0002,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0003,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0004,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0005,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0006,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0007,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0008,
    SpwRobot_GetScoreAndActionUnitLaunchSilo_0009,

    SpwRobot_GetScoreAndActionUnitLaunchFlare_0000,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0001,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0002,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0003,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0004,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0005,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0006,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0007,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0008,
    SpwRobot_GetScoreAndActionUnitLaunchFlare_0009,

    SpwRobot_GetBestScoreAndActionForCandidateUnit_0000,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0001,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0002,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0003,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0004,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0005,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0006,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0007,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0008,
    SpwRobot_GetBestScoreAndActionForCandidateUnit_0009,

    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0000,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0001,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0002,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0003,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0004,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0005,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0006,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0007,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0008,
    SpwRobot_GetBestScoreAndActionPlayerProduceUnitWithGridIndex_0009,

    SpwRobot_GetScoreAndActionUnitDive_0000,
    SpwRobot_GetScoreAndActionUnitDive_0001,
    SpwRobot_GetScoreAndActionUnitDive_0002,
    SpwRobot_GetScoreAndActionUnitDive_0003,
    SpwRobot_GetScoreAndActionUnitDive_0004,
    SpwRobot_GetScoreAndActionUnitDive_0005,
    SpwRobot_GetScoreAndActionUnitDive_0006,
    SpwRobot_GetScoreAndActionUnitDive_0007,
    SpwRobot_GetScoreAndActionUnitDive_0008,
    SpwRobot_GetScoreAndActionUnitDive_0009,

    SpwRobot_GetScoreAndActionUnitSurface_0000,
    SpwRobot_GetScoreAndActionUnitSurface_0001,
    SpwRobot_GetScoreAndActionUnitSurface_0002,
    SpwRobot_GetScoreAndActionUnitSurface_0003,
    SpwRobot_GetScoreAndActionUnitSurface_0004,
    SpwRobot_GetScoreAndActionUnitSurface_0005,
    SpwRobot_GetScoreAndActionUnitSurface_0006,
    SpwRobot_GetScoreAndActionUnitSurface_0007,
    SpwRobot_GetScoreAndActionUnitSurface_0008,
    SpwRobot_GetScoreAndActionUnitSurface_0009,

    SpwRobot_GetScoreAndActionUnitWait_0000,
    SpwRobot_GetScoreAndActionUnitWait_0001,
    SpwRobot_GetScoreAndActionUnitWait_0002,
    SpwRobot_GetScoreAndActionUnitWait_0003,
    SpwRobot_GetScoreAndActionUnitWait_0004,
    SpwRobot_GetScoreAndActionUnitWait_0005,
    SpwRobot_GetScoreAndActionUnitWait_0006,
    SpwRobot_GetScoreAndActionUnitWait_0007,
    SpwRobot_GetScoreAndActionUnitWait_0008,
    SpwRobot_GetScoreAndActionUnitWait_0009,

    SpwRobot_GetBestActionPlayerProduceUnit_0000,
    SpwRobot_GetBestActionPlayerProduceUnit_0001,
    SpwRobot_GetBestActionPlayerProduceUnit_0002,
    SpwRobot_GetBestActionPlayerProduceUnit_0003,
    SpwRobot_GetBestActionPlayerProduceUnit_0004,
    SpwRobot_GetBestActionPlayerProduceUnit_0005,
    SpwRobot_GetBestActionPlayerProduceUnit_0006,
    SpwRobot_GetBestActionPlayerProduceUnit_0007,
    SpwRobot_GetBestActionPlayerProduceUnit_0008,
    SpwRobot_GetBestActionPlayerProduceUnit_0009,

    SpwRobot_GetNextAction_0000,
    SpwRobot_GetNextAction_0001,
    SpwRobot_GetNextAction_0002,
    SpwRobot_GetNextAction_0003,
    SpwRobot_GetNextAction_0004,
    SpwRobot_GetNextAction_0005,
    SpwRobot_GetNextAction_0006,
    SpwRobot_GetNextAction_0007,
    SpwRobot_GetNextAction_0008,
    SpwRobot_GetNextAction_0009,

    SpwRobot_DoGetNextAction_0000,
    SpwRobot_DoGetNextAction_0001,
    SpwRobot_DoGetNextAction_0002,
    SpwRobot_DoGetNextAction_0003,
    SpwRobot_DoGetNextAction_0004,
    SpwRobot_DoGetNextAction_0005,
    SpwRobot_DoGetNextAction_0006,
    SpwRobot_DoGetNextAction_0007,
    SpwRobot_DoGetNextAction_0008,
    SpwRobot_DoGetNextAction_0009,

    SrwWar_Init_0000,
    SrwWar_Init_0001,
    SrwWar_Init_0002,
    SrwWar_Init_0003,
    SrwWar_Init_0004,
    SrwWar_Init_0005,
    SrwWar_Init_0006,
    SrwWar_Init_0007,
    SrwWar_Init_0008,
    SrwWar_Init_0009,

    BwWarDataHelper_CreateValidationDataForSrw_0000,
    BwWarDataHelper_CreateValidationDataForSrw_0001,
    BwWarDataHelper_CreateValidationDataForSrw_0002,
    BwWarDataHelper_CreateValidationDataForSrw_0003,
    BwWarDataHelper_CreateValidationDataForSrw_0004,
    BwWarDataHelper_CreateValidationDataForSrw_0005,
    BwWarDataHelper_CreateValidationDataForSrw_0006,
    BwWarDataHelper_CreateValidationDataForSrw_0007,
    BwWarDataHelper_CreateValidationDataForSrw_0008,
    BwWarDataHelper_CreateValidationDataForSrw_0009,
    BwWarDataHelper_CreateValidationDataForSrw_0010,
    BwWarDataHelper_CreateValidationDataForSrw_0011,
    BwWarDataHelper_CreateValidationDataForSrw_0012,
    BwWarDataHelper_CreateValidationDataForSrw_0013,
    BwWarDataHelper_CreateValidationDataForSrw_0014,
    BwWarDataHelper_CreateValidationDataForSrw_0015,
    BwWarDataHelper_CreateValidationDataForSrw_0016,
    BwWarDataHelper_CreateValidationDataForSrw_0017,
    BwWarDataHelper_CreateValidationDataForSrw_0018,
    BwWarDataHelper_CreateValidationDataForSrw_0019,

    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0000,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0001,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0002,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0003,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0004,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0005,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0006,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0007,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0008,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0009,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0010,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0011,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0012,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0013,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0014,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0015,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0016,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0017,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0018,
    BwWarDataHelper_CreateValidationPlayerManageDataForSrw_0019,

    IllegalRequest0000,
    IllegalRequest0001,
    IllegalRequest0002,
    IllegalRequest0003,

    MsgBroadcastAddMessage0000,
    MsgBroadcastAddMessage0001,
    MsgBroadcastAddMessage0002,
    MsgBroadcastAddMessage0003,
    MsgBroadcastAddMessage0004,
    MsgBroadcastAddMessage0005,
    MsgBroadcastAddMessage0006,

    MsgBroadcastDeleteMessage0000,
    MsgBroadcastDeleteMessage0001,
    MsgBroadcastDeleteMessage0002,
    MsgBroadcastDeleteMessage0003,

    MsgBroadcastDoBroadcast0000,
    MsgBroadcastDoBroadcast0001,

    MsgBroadcastGetMessageList0000,

    MsgChangeLogAddMessage0000,
    MsgChangeLogAddMessage0001,
    MsgChangeLogAddMessage0002,
    MsgChangeLogAddMessage0003,

    MsgChangeLogModifyMessage0000,
    MsgChangeLogModifyMessage0001,
    MsgChangeLogModifyMessage0002,
    MsgChangeLogModifyMessage0003,
    MsgChangeLogModifyMessage0004,

    MsgChangeLogGetMessageList0000,

    MsgChatAddMessage0000,
    MsgChatAddMessage0001,
    MsgChatAddMessage0002,
    MsgChatAddMessage0003,
    MsgChatAddMessage0004,

    MsgChatUpdateReadProgress0000,
    MsgChatUpdateReadProgress0001,
    MsgChatUpdateReadProgress0002,
    MsgChatUpdateReadProgress0003,
    MsgChatUpdateReadProgress0004,
    MsgChatUpdateReadProgress0005,
    MsgChatUpdateReadProgress0006,
    MsgChatUpdateReadProgress0007,
    MsgChatUpdateReadProgress0008,

    MsgMapGetBriefData0000,
    MsgMapGetBriefData0001,
    MsgMapGetBriefData0002,

    MsgMapGetEnabledBriefDataList0000,
    MsgMapGetEnabledBriefDataList0001,

    MsgMapGetEnabledRawDataList0000,
    MsgMapGetEnabledRawDataList0001,

    MsgMapGetRawData0000,
    MsgMapGetRawData0001,
    MsgMapGetRawData0002,

    MsgMeGetMapData0000,
    MsgMeGetMapData0001,
    MsgMeGetMapData0002,
    MsgMeGetMapData0003,

    MsgMeGetMapDataList0000,

    MsgMeGetSubmittedWarRuleList0000,

    MsgMeSubmitMap0000,
    MsgMeSubmitMap0001,
    MsgMeSubmitMap0002,
    MsgMeSubmitMap0003,
    MsgMeSubmitMap0004,
    MsgMeSubmitMap0005,

    MsgMeSubmitWarRule0000,
    MsgMeSubmitWarRule0001,
    MsgMeSubmitWarRule0002,
    MsgMeSubmitWarRule0003,
    MsgMeSubmitWarRule0004,
    MsgMeSubmitWarRule0005,
    MsgMeSubmitWarRule0006,
    MsgMeSubmitWarRule0007,
    MsgMeSubmitWarRule0008,

    MsgMmSetMapEnabled0000,
    MsgMmSetMapEnabled0001,
    MsgMmSetMapEnabled0002,
    MsgMmSetMapEnabled0003,
    MsgMmSetMapEnabled0004,
    MsgMmSetMapEnabled0005,
    MsgMmSetMapEnabled0006,
    MsgMmSetMapEnabled0007,
    MsgMmSetMapEnabled0008,

    MsgMmGetReviewingMaps0000,
    MsgMmGetReviewingMaps0001,
    MsgMmGetReviewingMaps0002,
    MsgMmGetReviewingMaps0003,

    MsgMmGetReviewingWarRuleList0000,
    MsgMmGetReviewingWarRuleList0001,
    MsgMmGetReviewingWarRuleList0002,
    MsgMmGetReviewingWarRuleList0003,

    MsgMmReviewMap0000,
    MsgMmReviewMap0001,
    MsgMmReviewMap0002,
    MsgMmReviewMap0003,
    MsgMmReviewMap0004,
    MsgMmReviewMap0005,
    MsgMmReviewMap0006,
    MsgMmReviewMap0007,
    MsgMmReviewMap0008,
    MsgMmReviewMap0009,

    MsgMmReviewWarRule0000,
    MsgMmReviewWarRule0001,
    MsgMmReviewWarRule0002,
    MsgMmReviewWarRule0003,
    MsgMmReviewWarRule0004,
    MsgMmReviewWarRule0005,
    MsgMmReviewWarRule0006,
    MsgMmReviewWarRule0007,
    MsgMmReviewWarRule0008,
    MsgMmReviewWarRule0009,
    MsgMmReviewWarRule0010,
    MsgMmReviewWarRule0011,

    MsgMmSetMapAvailability0000,
    MsgMmSetMapAvailability0001,
    MsgMmSetMapAvailability0002,
    MsgMmSetMapAvailability0003,
    MsgMmSetMapAvailability0004,
    MsgMmSetMapAvailability0005,
    MsgMmSetMapAvailability0006,
    MsgMmSetMapAvailability0007,
    MsgMmSetMapAvailability0008,
    MsgMmSetMapAvailability0009,

    MsgMmSetMapTag0000,
    MsgMmSetMapTag0001,
    MsgMmSetMapTag0002,
    MsgMmSetMapTag0003,
    MsgMmSetMapTag0004,
    MsgMmSetMapTag0005,
    MsgMmSetMapTag0006,
    MsgMmSetMapTag0007,

    MsgMcrCreateRoom0000,
    MsgMcrCreateRoom0001,
    MsgMcrCreateRoom0002,
    MsgMcrCreateRoom0003,
    MsgMcrCreateRoom0004,
    MsgMcrCreateRoom0005,
    MsgMcrCreateRoom0006,
    MsgMcrCreateRoom0007,
    MsgMcrCreateRoom0008,
    MsgMcrCreateRoom0009,
    MsgMcrCreateRoom0010,
    MsgMcrCreateRoom0011,
    MsgMcrCreateRoom0012,
    MsgMcrCreateRoom0013,
    MsgMcrCreateRoom0014,
    MsgMcrCreateRoom0015,
    MsgMcrCreateRoom0016,
    MsgMcrCreateRoom0017,
    MsgMcrCreateRoom0018,
    MsgMcrCreateRoom0019,

    MsgMcrDeletePlayer0000,
    MsgMcrDeletePlayer0001,
    MsgMcrDeletePlayer0002,
    MsgMcrDeletePlayer0003,
    MsgMcrDeletePlayer0004,
    MsgMcrDeletePlayer0005,
    MsgMcrDeletePlayer0006,
    MsgMcrDeletePlayer0007,

    MsgMcrDeleteRoom0000,
    MsgMcrDeleteRoom0001,
    MsgMcrDeleteRoom0002,
    MsgMcrDeleteRoom0003,

    MsgMcrExitRoom0000,
    MsgMcrExitRoom0001,
    MsgMcrExitRoom0002,
    MsgMcrExitRoom0003,
    MsgMcrExitRoom0004,
    MsgMcrExitRoom0005,

    MsgMcrGetRoomInfo0000,

    MsgMcrJoinRoom0000,
    MsgMcrJoinRoom0001,
    MsgMcrJoinRoom0002,
    MsgMcrJoinRoom0003,
    MsgMcrJoinRoom0004,
    MsgMcrJoinRoom0005,
    MsgMcrJoinRoom0006,
    MsgMcrJoinRoom0007,
    MsgMcrJoinRoom0008,
    MsgMcrJoinRoom0009,
    MsgMcrJoinRoom0010,
    MsgMcrJoinRoom0011,
    MsgMcrJoinRoom0012,
    MsgMcrJoinRoom0013,
    MsgMcrJoinRoom0014,
    MsgMcrJoinRoom0015,
    MsgMcrJoinRoom0016,
    MsgMcrJoinRoom0017,
    MsgMcrJoinRoom0018,
    MsgMcrJoinRoom0019,
    MsgMcrJoinRoom0020,

    MsgMcrSetReady0000,
    MsgMcrSetReady0001,
    MsgMcrSetReady0002,
    MsgMcrSetReady0003,
    MsgMcrSetReady0004,
    MsgMcrSetReady0005,

    MsgMcrSetSelfSettings0000,
    MsgMcrSetSelfSettings0001,
    MsgMcrSetSelfSettings0002,
    MsgMcrSetSelfSettings0003,
    MsgMcrSetSelfSettings0004,
    MsgMcrSetSelfSettings0005,
    MsgMcrSetSelfSettings0006,
    MsgMcrSetSelfSettings0007,
    MsgMcrSetSelfSettings0008,
    MsgMcrSetSelfSettings0009,
    MsgMcrSetSelfSettings0010,
    MsgMcrSetSelfSettings0011,
    MsgMcrSetSelfSettings0012,
    MsgMcrSetSelfSettings0013,
    MsgMcrSetSelfSettings0014,
    MsgMcrSetSelfSettings0015,
    MsgMcrSetSelfSettings0016,

    MsgMcrSetWarRule0000,
    MsgMcrSetWarRule0001,
    MsgMcrSetWarRule0002,
    MsgMcrSetWarRule0003,
    MsgMcrSetWarRule0004,
    MsgMcrSetWarRule0005,
    MsgMcrSetWarRule0006,
    MsgMcrSetWarRule0007,
    MsgMcrSetWarRule0008,
    MsgMcrSetWarRule0009,
    MsgMcrSetWarRule0010,
    MsgMcrSetWarRule0011,
    MsgMcrSetWarRule0012,
    MsgMcrSetWarRule0013,
    MsgMcrSetWarRule0014,
    MsgMcrSetWarRule0015,
    MsgMcrSetWarRule0016,

    MsgMcrStartWar0000,
    MsgMcrStartWar0001,
    MsgMcrStartWar0002,
    MsgMcrStartWar0003,
    MsgMcrStartWar0004,
    MsgMcrStartWar0005,
    MsgMcrStartWar0006,
    MsgMcrStartWar0007,
    MsgMcrStartWar0008,
    MsgMcrStartWar0009,
    MsgMcrStartWar0010,
    MsgMcrStartWar0011,

    MsgMfrCreateRoom0000,
    MsgMfrCreateRoom0001,
    MsgMfrCreateRoom0002,
    MsgMfrCreateRoom0003,
    MsgMfrCreateRoom0004,
    MsgMfrCreateRoom0005,
    MsgMfrCreateRoom0006,
    MsgMfrCreateRoom0007,
    MsgMfrCreateRoom0008,
    MsgMfrCreateRoom0009,
    MsgMfrCreateRoom0010,
    MsgMfrCreateRoom0011,
    MsgMfrCreateRoom0012,
    MsgMfrCreateRoom0013,
    MsgMfrCreateRoom0014,
    MsgMfrCreateRoom0015,
    MsgMfrCreateRoom0016,
    MsgMfrCreateRoom0017,
    MsgMfrCreateRoom0018,
    MsgMfrCreateRoom0019,

    MsgMfrExitRoom0000,
    MsgMfrExitRoom0001,
    MsgMfrExitRoom0002,
    MsgMfrExitRoom0003,
    MsgMfrExitRoom0004,
    MsgMfrExitRoom0005,

    MsgMfrDeletePlayer0000,
    MsgMfrDeletePlayer0001,
    MsgMfrDeletePlayer0002,
    MsgMfrDeletePlayer0003,
    MsgMfrDeletePlayer0004,
    MsgMfrDeletePlayer0005,
    MsgMfrDeletePlayer0006,
    MsgMfrDeletePlayer0007,

    MsgMfrDeleteRoom0000,
    MsgMfrDeleteRoom0001,
    MsgMfrDeleteRoom0002,
    MsgMfrDeleteRoom0003,

    MsgMfrGetRoomInfo0000,

    MsgMfrJoinRoom0000,
    MsgMfrJoinRoom0001,
    MsgMfrJoinRoom0002,
    MsgMfrJoinRoom0003,
    MsgMfrJoinRoom0004,
    MsgMfrJoinRoom0005,
    MsgMfrJoinRoom0006,
    MsgMfrJoinRoom0007,
    MsgMfrJoinRoom0008,
    MsgMfrJoinRoom0009,
    MsgMfrJoinRoom0010,
    MsgMfrJoinRoom0011,
    MsgMfrJoinRoom0012,
    MsgMfrJoinRoom0013,
    MsgMfrJoinRoom0014,
    MsgMfrJoinRoom0015,
    MsgMfrJoinRoom0016,
    MsgMfrJoinRoom0017,
    MsgMfrJoinRoom0018,
    MsgMfrJoinRoom0019,
    MsgMfrJoinRoom0020,

    MsgMfrSetReady0000,
    MsgMfrSetReady0001,
    MsgMfrSetReady0002,
    MsgMfrSetReady0003,
    MsgMfrSetReady0004,
    MsgMfrSetReady0005,

    MsgMfrSetSelfSettings0000,
    MsgMfrSetSelfSettings0001,
    MsgMfrSetSelfSettings0002,
    MsgMfrSetSelfSettings0003,
    MsgMfrSetSelfSettings0004,
    MsgMfrSetSelfSettings0005,
    MsgMfrSetSelfSettings0006,
    MsgMfrSetSelfSettings0007,
    MsgMfrSetSelfSettings0008,
    MsgMfrSetSelfSettings0009,
    MsgMfrSetSelfSettings0010,
    MsgMfrSetSelfSettings0011,
    MsgMfrSetSelfSettings0012,
    MsgMfrSetSelfSettings0013,
    MsgMfrSetSelfSettings0014,

    MsgMfrStartWar0000,
    MsgMfrStartWar0001,
    MsgMfrStartWar0002,
    MsgMfrStartWar0003,
    MsgMfrStartWar0004,
    MsgMfrStartWar0005,
    MsgMfrStartWar0006,
    MsgMfrStartWar0007,
    MsgMfrStartWar0008,

    MsgMpwActionPlayerDeleteUnit0000,
    MsgMpwActionPlayerDeleteUnit0001,
    MsgMpwActionPlayerDeleteUnit0002,
    MsgMpwActionPlayerDeleteUnit0003,
    MsgMpwActionPlayerDeleteUnit0004,
    MsgMpwActionPlayerDeleteUnit0005,
    MsgMpwActionPlayerDeleteUnit0006,
    MsgMpwActionPlayerDeleteUnit0007,
    MsgMpwActionPlayerDeleteUnit0008,
    MsgMpwActionPlayerDeleteUnit0009,
    MsgMpwActionPlayerDeleteUnit0010,
    MsgMpwActionPlayerDeleteUnit0011,

    MsgMpwActionPlayerEndTurn0000,
    MsgMpwActionPlayerEndTurn0001,
    MsgMpwActionPlayerEndTurn0002,
    MsgMpwActionPlayerEndTurn0003,
    MsgMpwActionPlayerEndTurn0004,
    MsgMpwActionPlayerEndTurn0005,
    MsgMpwActionPlayerEndTurn0006,
    MsgMpwActionPlayerEndTurn0007,
    MsgMpwActionPlayerEndTurn0008,
    MsgMpwActionPlayerEndTurn0009,

    MsgMpwActionPlayerProduceUnit0000,
    MsgMpwActionPlayerProduceUnit0001,
    MsgMpwActionPlayerProduceUnit0002,
    MsgMpwActionPlayerProduceUnit0003,
    MsgMpwActionPlayerProduceUnit0004,
    MsgMpwActionPlayerProduceUnit0005,
    MsgMpwActionPlayerProduceUnit0006,
    MsgMpwActionPlayerProduceUnit0007,
    MsgMpwActionPlayerProduceUnit0008,
    MsgMpwActionPlayerProduceUnit0009,
    MsgMpwActionPlayerProduceUnit0010,
    MsgMpwActionPlayerProduceUnit0011,
    MsgMpwActionPlayerProduceUnit0012,
    MsgMpwActionPlayerProduceUnit0013,
    MsgMpwActionPlayerProduceUnit0014,
    MsgMpwActionPlayerProduceUnit0015,
    MsgMpwActionPlayerProduceUnit0016,
    MsgMpwActionPlayerProduceUnit0017,
    MsgMpwActionPlayerProduceUnit0018,
    MsgMpwActionPlayerProduceUnit0019,
    MsgMpwActionPlayerProduceUnit0020,
    MsgMpwActionPlayerProduceUnit0021,
    MsgMpwActionPlayerProduceUnit0022,
    MsgMpwActionPlayerProduceUnit0023,

    MsgMpwActionPlayerSurrender0000,
    MsgMpwActionPlayerSurrender0001,
    MsgMpwActionPlayerSurrender0002,
    MsgMpwActionPlayerSurrender0003,
    MsgMpwActionPlayerSurrender0004,
    MsgMpwActionPlayerSurrender0005,
    MsgMpwActionPlayerSurrender0006,
    MsgMpwActionPlayerSurrender0007,
    MsgMpwActionPlayerSurrender0008,
    MsgMpwActionPlayerSurrender0009,

    MsgMpwActionPlayerVoteForDraw0000,
    MsgMpwActionPlayerVoteForDraw0001,
    MsgMpwActionPlayerVoteForDraw0002,
    MsgMpwActionPlayerVoteForDraw0003,
    MsgMpwActionPlayerVoteForDraw0004,
    MsgMpwActionPlayerVoteForDraw0005,
    MsgMpwActionPlayerVoteForDraw0006,
    MsgMpwActionPlayerVoteForDraw0007,
    MsgMpwActionPlayerVoteForDraw0008,
    MsgMpwActionPlayerVoteForDraw0009,

    MsgMpwActionUnitAttackTile0000,
    MsgMpwActionUnitAttackTile0001,
    MsgMpwActionUnitAttackTile0002,
    MsgMpwActionUnitAttackTile0003,
    MsgMpwActionUnitAttackTile0004,
    MsgMpwActionUnitAttackTile0005,
    MsgMpwActionUnitAttackTile0006,
    MsgMpwActionUnitAttackTile0007,
    MsgMpwActionUnitAttackTile0008,
    MsgMpwActionUnitAttackTile0009,
    MsgMpwActionUnitAttackTile0010,
    MsgMpwActionUnitAttackTile0011,
    MsgMpwActionUnitAttackTile0012,
    MsgMpwActionUnitAttackTile0013,
    MsgMpwActionUnitAttackTile0014,
    MsgMpwActionUnitAttackTile0015,
    MsgMpwActionUnitAttackTile0016,

    MsgMpwActionUnitAttackUnit0000,
    MsgMpwActionUnitAttackUnit0001,
    MsgMpwActionUnitAttackUnit0002,
    MsgMpwActionUnitAttackUnit0003,
    MsgMpwActionUnitAttackUnit0004,
    MsgMpwActionUnitAttackUnit0005,
    MsgMpwActionUnitAttackUnit0006,
    MsgMpwActionUnitAttackUnit0007,
    MsgMpwActionUnitAttackUnit0008,
    MsgMpwActionUnitAttackUnit0009,
    MsgMpwActionUnitAttackUnit0010,
    MsgMpwActionUnitAttackUnit0011,
    MsgMpwActionUnitAttackUnit0012,
    MsgMpwActionUnitAttackUnit0013,
    MsgMpwActionUnitAttackUnit0014,
    MsgMpwActionUnitAttackUnit0015,
    MsgMpwActionUnitAttackUnit0016,

    MsgMpwActionUnitBeLoaded0000,
    MsgMpwActionUnitBeLoaded0001,
    MsgMpwActionUnitBeLoaded0002,
    MsgMpwActionUnitBeLoaded0003,
    MsgMpwActionUnitBeLoaded0004,
    MsgMpwActionUnitBeLoaded0005,
    MsgMpwActionUnitBeLoaded0006,
    MsgMpwActionUnitBeLoaded0007,
    MsgMpwActionUnitBeLoaded0008,
    MsgMpwActionUnitBeLoaded0009,
    MsgMpwActionUnitBeLoaded0010,

    MsgMpwActionUnitBuildTile0000,
    MsgMpwActionUnitBuildTile0001,
    MsgMpwActionUnitBuildTile0002,
    MsgMpwActionUnitBuildTile0003,
    MsgMpwActionUnitBuildTile0004,
    MsgMpwActionUnitBuildTile0005,
    MsgMpwActionUnitBuildTile0006,
    MsgMpwActionUnitBuildTile0007,
    MsgMpwActionUnitBuildTile0008,
    MsgMpwActionUnitBuildTile0009,
    MsgMpwActionUnitBuildTile0010,
    MsgMpwActionUnitBuildTile0011,
    MsgMpwActionUnitBuildTile0012,

    MsgMpwActionUnitCaptureTile0000,
    MsgMpwActionUnitCaptureTile0001,
    MsgMpwActionUnitCaptureTile0002,
    MsgMpwActionUnitCaptureTile0003,
    MsgMpwActionUnitCaptureTile0004,
    MsgMpwActionUnitCaptureTile0005,
    MsgMpwActionUnitCaptureTile0006,
    MsgMpwActionUnitCaptureTile0007,
    MsgMpwActionUnitCaptureTile0008,
    MsgMpwActionUnitCaptureTile0009,
    MsgMpwActionUnitCaptureTile0010,
    MsgMpwActionUnitCaptureTile0011,
    MsgMpwActionUnitCaptureTile0012,
    MsgMpwActionUnitCaptureTile0013,

    MsgMpwActionUnitDive0000,
    MsgMpwActionUnitDive0001,
    MsgMpwActionUnitDive0002,
    MsgMpwActionUnitDive0003,
    MsgMpwActionUnitDive0004,
    MsgMpwActionUnitDive0005,
    MsgMpwActionUnitDive0006,
    MsgMpwActionUnitDive0007,
    MsgMpwActionUnitDive0008,
    MsgMpwActionUnitDive0009,
    MsgMpwActionUnitDive0010,
    MsgMpwActionUnitDive0011,

    MsgMpwActionUnitDropUnit0000,
    MsgMpwActionUnitDropUnit0001,
    MsgMpwActionUnitDropUnit0002,
    MsgMpwActionUnitDropUnit0003,
    MsgMpwActionUnitDropUnit0004,
    MsgMpwActionUnitDropUnit0005,
    MsgMpwActionUnitDropUnit0006,
    MsgMpwActionUnitDropUnit0007,
    MsgMpwActionUnitDropUnit0008,
    MsgMpwActionUnitDropUnit0009,
    MsgMpwActionUnitDropUnit0010,

    MsgMpwActionUnitJoinUnit0000,
    MsgMpwActionUnitJoinUnit0001,
    MsgMpwActionUnitJoinUnit0002,
    MsgMpwActionUnitJoinUnit0003,
    MsgMpwActionUnitJoinUnit0004,
    MsgMpwActionUnitJoinUnit0005,
    MsgMpwActionUnitJoinUnit0006,
    MsgMpwActionUnitJoinUnit0007,
    MsgMpwActionUnitJoinUnit0008,
    MsgMpwActionUnitJoinUnit0009,
    MsgMpwActionUnitJoinUnit0010,
    MsgMpwActionUnitJoinUnit0011,

    MsgMpwActionUnitLaunchFlare0000,
    MsgMpwActionUnitLaunchFlare0001,
    MsgMpwActionUnitLaunchFlare0002,
    MsgMpwActionUnitLaunchFlare0003,
    MsgMpwActionUnitLaunchFlare0004,
    MsgMpwActionUnitLaunchFlare0005,
    MsgMpwActionUnitLaunchFlare0006,
    MsgMpwActionUnitLaunchFlare0007,
    MsgMpwActionUnitLaunchFlare0008,
    MsgMpwActionUnitLaunchFlare0009,
    MsgMpwActionUnitLaunchFlare0010,
    MsgMpwActionUnitLaunchFlare0011,
    MsgMpwActionUnitLaunchFlare0012,
    MsgMpwActionUnitLaunchFlare0013,
    MsgMpwActionUnitLaunchFlare0014,
    MsgMpwActionUnitLaunchFlare0015,

    MsgMpwActionUnitLaunchSilo0000,
    MsgMpwActionUnitLaunchSilo0001,
    MsgMpwActionUnitLaunchSilo0002,
    MsgMpwActionUnitLaunchSilo0003,
    MsgMpwActionUnitLaunchSilo0004,
    MsgMpwActionUnitLaunchSilo0005,
    MsgMpwActionUnitLaunchSilo0006,
    MsgMpwActionUnitLaunchSilo0007,
    MsgMpwActionUnitLaunchSilo0008,
    MsgMpwActionUnitLaunchSilo0009,
    MsgMpwActionUnitLaunchSilo0010,
    MsgMpwActionUnitLaunchSilo0011,
    MsgMpwActionUnitLaunchSilo0012,
    MsgMpwActionUnitLaunchSilo0013,
    MsgMpwActionUnitLaunchSilo0014,

    MsgMpwActionUnitLoadCo0000,
    MsgMpwActionUnitLoadCo0001,
    MsgMpwActionUnitLoadCo0002,
    MsgMpwActionUnitLoadCo0003,
    MsgMpwActionUnitLoadCo0004,
    MsgMpwActionUnitLoadCo0005,
    MsgMpwActionUnitLoadCo0006,
    MsgMpwActionUnitLoadCo0007,
    MsgMpwActionUnitLoadCo0008,
    MsgMpwActionUnitLoadCo0009,
    MsgMpwActionUnitLoadCo0010,

    MsgMpwActionUnitProduceUnit0000,
    MsgMpwActionUnitProduceUnit0001,
    MsgMpwActionUnitProduceUnit0002,
    MsgMpwActionUnitProduceUnit0003,
    MsgMpwActionUnitProduceUnit0004,
    MsgMpwActionUnitProduceUnit0005,
    MsgMpwActionUnitProduceUnit0006,
    MsgMpwActionUnitProduceUnit0007,
    MsgMpwActionUnitProduceUnit0008,
    MsgMpwActionUnitProduceUnit0009,
    MsgMpwActionUnitProduceUnit0010,
    MsgMpwActionUnitProduceUnit0011,
    MsgMpwActionUnitProduceUnit0012,

    MsgMpwActionUnitSupplyUnit0000,
    MsgMpwActionUnitSupplyUnit0001,
    MsgMpwActionUnitSupplyUnit0002,
    MsgMpwActionUnitSupplyUnit0003,
    MsgMpwActionUnitSupplyUnit0004,
    MsgMpwActionUnitSupplyUnit0005,
    MsgMpwActionUnitSupplyUnit0006,
    MsgMpwActionUnitSupplyUnit0007,
    MsgMpwActionUnitSupplyUnit0008,
    MsgMpwActionUnitSupplyUnit0009,
    MsgMpwActionUnitSupplyUnit0010,
    MsgMpwActionUnitSupplyUnit0011,

    MsgMpwActionUnitSurface0000,
    MsgMpwActionUnitSurface0001,
    MsgMpwActionUnitSurface0002,
    MsgMpwActionUnitSurface0003,
    MsgMpwActionUnitSurface0004,
    MsgMpwActionUnitSurface0005,
    MsgMpwActionUnitSurface0006,
    MsgMpwActionUnitSurface0007,
    MsgMpwActionUnitSurface0008,
    MsgMpwActionUnitSurface0009,
    MsgMpwActionUnitSurface0010,
    MsgMpwActionUnitSurface0011,

    MsgMpwActionUnitUseCoSkill0000,
    MsgMpwActionUnitUseCoSkill0001,
    MsgMpwActionUnitUseCoSkill0002,
    MsgMpwActionUnitUseCoSkill0003,
    MsgMpwActionUnitUseCoSkill0004,
    MsgMpwActionUnitUseCoSkill0005,
    MsgMpwActionUnitUseCoSkill0006,
    MsgMpwActionUnitUseCoSkill0007,
    MsgMpwActionUnitUseCoSkill0008,
    MsgMpwActionUnitUseCoSkill0009,
    MsgMpwActionUnitUseCoSkill0010,

    MsgMpwActionUnitWait0000,
    MsgMpwActionUnitWait0001,
    MsgMpwActionUnitWait0002,
    MsgMpwActionUnitWait0003,
    MsgMpwActionUnitWait0004,
    MsgMpwActionUnitWait0005,
    MsgMpwActionUnitWait0006,
    MsgMpwActionUnitWait0007,
    MsgMpwActionUnitWait0008,

    MsgMpwCommonContinueWar0000,
    MsgMpwCommonContinueWar0001,
    MsgMpwCommonContinueWar0002,
    MsgMpwCommonContinueWar0003,

    MsgMpwCommonHandleBoot0000,
    MsgMpwCommonHandleBoot0001,

    MsgMpwCommonSyncWar0000,
    MsgMpwCommonSyncWar0001,
    MsgMpwCommonSyncWar0002,
    MsgMpwCommonSyncWar0003,

    MsgMpwWatchContinueWar0000,
    MsgMpwWatchContinueWar0001,
    MsgMpwWatchContinueWar0002,

    MsgMpwWatchDeleteWatcher0000,
    MsgMpwWatchDeleteWatcher0001,
    MsgMpwWatchDeleteWatcher0002,
    MsgMpwWatchDeleteWatcher0003,
    MsgMpwWatchDeleteWatcher0004,
    MsgMpwWatchDeleteWatcher0005,

    MsgMpwWatchHandleRequest0000,
    MsgMpwWatchHandleRequest0001,
    MsgMpwWatchHandleRequest0002,
    MsgMpwWatchHandleRequest0003,
    MsgMpwWatchHandleRequest0004,
    MsgMpwWatchHandleRequest0005,
    MsgMpwWatchHandleRequest0006,
    MsgMpwWatchHandleRequest0007,

    MsgMpwWatchMakeRequest0000,
    MsgMpwWatchMakeRequest0001,
    MsgMpwWatchMakeRequest0002,
    MsgMpwWatchMakeRequest0003,
    MsgMpwWatchMakeRequest0004,
    MsgMpwWatchMakeRequest0005,
    MsgMpwWatchMakeRequest0006,
    MsgMpwWatchMakeRequest0007,

    MsgMrrGetMaxConcurrentCount0000,

    MsgMrrGetMyRoomPublicInfoList0000,
    MsgMrrGetMyRoomPublicInfoList0001,

    MsgMrrGetRoomPublicInfo0000,
    MsgMrrGetRoomPublicInfo0001,

    MsgMrrSetBannedCoIdList0000,
    MsgMrrSetBannedCoIdList0001,
    MsgMrrSetBannedCoIdList0002,
    MsgMrrSetBannedCoIdList0003,
    MsgMrrSetBannedCoIdList0004,
    MsgMrrSetBannedCoIdList0005,
    MsgMrrSetBannedCoIdList0006,
    MsgMrrSetBannedCoIdList0007,
    MsgMrrSetBannedCoIdList0008,
    MsgMrrSetBannedCoIdList0009,
    MsgMrrSetBannedCoIdList0010,
    MsgMrrSetBannedCoIdList0011,
    MsgMrrSetBannedCoIdList0012,
    MsgMrrSetBannedCoIdList0013,
    MsgMrrSetBannedCoIdList0014,
    MsgMrrSetBannedCoIdList0015,
    MsgMrrSetBannedCoIdList0016,
    MsgMrrSetBannedCoIdList0017,

    MsgMrrSetMaxConcurrentCount0000,
    MsgMrrSetMaxConcurrentCount0001,
    MsgMrrSetMaxConcurrentCount0002,

    MsgMrrSetSelfSettings0000,
    MsgMrrSetSelfSettings0001,
    MsgMrrSetSelfSettings0002,
    MsgMrrSetSelfSettings0003,
    MsgMrrSetSelfSettings0004,
    MsgMrrSetSelfSettings0005,
    MsgMrrSetSelfSettings0006,
    MsgMrrSetSelfSettings0007,
    MsgMrrSetSelfSettings0008,
    MsgMrrSetSelfSettings0009,
    MsgMrrSetSelfSettings0010,
    MsgMrrSetSelfSettings0011,
    MsgMrrSetSelfSettings0012,
    MsgMrrSetSelfSettings0013,
    MsgMrrSetSelfSettings0014,
    MsgMrrSetSelfSettings0015,

    MsgReplayGetData0000,
    MsgReplayGetData0001,

    MsgReplaySetRating0000,
    MsgReplaySetRating0001,

    MsgScrContinueWar0000,
    MsgScrContinueWar0001,

    MsgSpmCreateSfw0000,
    MsgSpmCreateSfw0001,
    MsgSpmCreateSfw0002,
    MsgSpmCreateSfw0003,
    MsgSpmCreateSfw0004,
    MsgSpmCreateSfw0005,

    MsgSpmCreateScw0000,
    MsgSpmCreateScw0001,
    MsgSpmCreateScw0002,
    MsgSpmCreateScw0003,
    MsgSpmCreateScw0004,
    MsgSpmCreateScw0005,
    MsgSpmCreateScw0006,
    MsgSpmCreateScw0007,
    MsgSpmCreateScw0008,
    MsgSpmCreateScw0009,
    MsgSpmCreateScw0010,
    MsgSpmCreateScw0011,
    MsgSpmCreateScw0012,
    MsgSpmCreateScw0013,
    MsgSpmCreateScw0014,
    MsgSpmCreateScw0015,
    MsgSpmCreateScw0016,
    MsgSpmCreateScw0017,
    MsgSpmCreateScw0018,

    MsgSpmCreateSrw0000,
    MsgSpmCreateSrw0001,
    MsgSpmCreateSrw0002,
    MsgSpmCreateSrw0003,
    MsgSpmCreateSrw0004,
    MsgSpmCreateSrw0005,
    MsgSpmCreateSrw0006,
    MsgSpmCreateSrw0007,
    MsgSpmCreateSrw0008,
    MsgSpmCreateSrw0009,
    MsgSpmCreateSrw0010,
    MsgSpmCreateSrw0011,
    MsgSpmCreateSrw0012,
    MsgSpmCreateSrw0013,
    MsgSpmCreateSrw0014,
    MsgSpmCreateSrw0015,
    MsgSpmCreateSrw0016,
    MsgSpmCreateSrw0017,
    MsgSpmCreateSrw0018,
    MsgSpmCreateSrw0019,
    MsgSpmCreateSrw0020,

    MsgScrDeleteWar0000,

    MsgSpmSaveScw0000,
    MsgSpmSaveScw0001,
    MsgSpmSaveScw0002,
    MsgSpmSaveScw0003,

    MsgSpmSaveSfw0000,
    MsgSpmSaveSfw0001,
    MsgSpmSaveSfw0002,
    MsgSpmSaveSfw0003,

    MsgSpmSaveSrw0000,
    MsgSpmSaveSrw0001,
    MsgSpmSaveSrw0002,
    MsgSpmSaveSrw0003,
    MsgSpmSaveSrw0004,
    MsgSpmSaveSrw0005,
    MsgSpmSaveSrw0006,
    MsgSpmSaveSrw0007,
    MsgSpmSaveSrw0008,
    MsgSpmSaveSrw0009,

    MsgSpmValidateSrw0000,
    MsgSpmValidateSrw0001,
    MsgSpmValidateSrw0002,
    MsgSpmValidateSrw0003,
    MsgSpmValidateSrw0004,
    MsgSpmValidateSrw0005,
    MsgSpmValidateSrw0006,
    MsgSpmValidateSrw0007,
    MsgSpmValidateSrw0008,
    MsgSpmValidateSrw0009,
    MsgSpmValidateSrw0010,
    MsgSpmValidateSrw0011,
    MsgSpmValidateSrw0012,
    MsgSpmValidateSrw0013,
    MsgSpmValidateSrw0014,
    MsgSpmValidateSrw0015,
    MsgSpmValidateSrw0016,
    MsgSpmValidateSrw0017,
    MsgSpmValidateSrw0018,
    MsgSpmValidateSrw0019,

    MsgSpmGetSrwRankInfo0000,
    MsgSpmGetSrwRankInfo0001,
    MsgSpmGetSrwRankInfo0002,
    MsgSpmGetSrwRankInfo0003,
    MsgSpmGetSrwRankInfo0004,
    MsgSpmGetSrwRankInfo0005,
    MsgSpmGetSrwRankInfo0006,
    MsgSpmGetSrwRankInfo0007,
    MsgSpmGetSrwRankInfo0008,
    MsgSpmGetSrwRankInfo0009,

    MsgUserGetPublicInfo0000,
    MsgUserGetPublicInfo0001,

    MsgUserGetSettings0000,

    MsgUserLogin0000,                   // socket已有user id
    MsgUserLogin0001,                   // 账号不合法
    MsgUserLogin0002,                   // 已处于已登录的状态
    MsgUserLogin0003,                   // 密码不合法
    MsgUserLogin0004,
    MsgUserLogin0005,                   // 账号不存在
    MsgUserLogin0006,                   // 账号或密码不正确
    MsgUserLogin0007,                   // 账号权限设定不存在
    MsgUserLogin0008,                   // 账号无权登录

    MsgUserRegister0000,                // 账号不合法
    MsgUserRegister0001,                // 账号已存在
    MsgUserRegister0002,                // 已处于已登录的状态
    MsgUserRegister0003,                // 密码不合法
    MsgUserRegister0004,                // 昵称不合法
    MsgUserRegister0005,                // 昵称已被使用

    MsgUserSetDiscordId0000,

    MsgUserSetNickname0000,             // 昵称不合法
    MsgUserSetNickname0001,             // 昵称已被使用

    MsgUserSetPassword0000,
    MsgUserSetPassword0001,
    MsgUserSetPassword0002,

    MsgUserSetPrivilege0000,
    MsgUserSetPrivilege0001,
    MsgUserSetPrivilege0002,
    MsgUserSetPrivilege0003,
    MsgUserSetPrivilege0004,

    MsgUserSetSettings0000,
    MsgUserSetSettings0001,
    MsgUserSetSettings0002,
}
}
