
namespace TinyWars.Utility {
export enum WarActionCodes {
ActionPlayerBeginTurn = 11,
ActionPlayerEndTurn = 12,
ActionPlayerSurrender = 13,
ActionPlayerProduceUnit = 14,
ActionPlayerDeleteUnit = 15,
ActionPlayerVoteForDraw = 16,
ActionUnitWait = 17,
ActionUnitBeLoaded = 18,
ActionUnitCaptureTile = 19,
ActionUnitAttack = 20,
ActionUnitDrop = 21,
ActionUnitBuildTile = 22,
ActionUnitDive = 23,
ActionUnitSurface = 24,
ActionUnitJoin = 25,
ActionUnitLaunchFlare = 26,
ActionUnitLaunchSilo = 27,
ActionUnitProduceUnit = 28,
ActionUnitSupply = 29,
ActionUnitLoadCo = 30,
ActionUnitUseCoSkill = 31,
}}
