
namespace TinyWars.Utility {
export enum WarActionCodes {
ActionSystemBeginTurn = 10,
ActionSystemCallWarEvent = 11,
ActionSystemDestroyPlayerForce = 12,
ActionSystemEndWar = 13,
ActionPlayerEndTurn = 20,
ActionPlayerSurrender = 21,
ActionPlayerProduceUnit = 22,
ActionPlayerDeleteUnit = 23,
ActionPlayerVoteForDraw = 24,
ActionUnitWait = 30,
ActionUnitBeLoaded = 31,
ActionUnitCaptureTile = 32,
ActionUnitAttackTile = 33,
ActionUnitAttackUnit = 34,
ActionUnitDropUnit = 35,
ActionUnitBuildTile = 36,
ActionUnitDive = 37,
ActionUnitSurface = 38,
ActionUnitJoinUnit = 39,
ActionUnitLaunchFlare = 40,
ActionUnitLaunchSilo = 41,
ActionUnitProduceUnit = 42,
ActionUnitSupplyUnit = 43,
ActionUnitLoadCo = 44,
ActionUnitUseCoSkill = 45,
}}
