
namespace Utility {
export enum WarActionCodes {
WarActionSystemBeginTurn = 10,
WarActionSystemCallWarEvent = 11,
WarActionSystemDestroyPlayerForce = 12,
WarActionSystemEndWar = 13,
WarActionSystemEndTurn = 14,
WarActionSystemHandleBootPlayer = 15,
WarActionPlayerEndTurn = 20,
WarActionPlayerSurrender = 21,
WarActionPlayerProduceUnit = 22,
WarActionPlayerDeleteUnit = 23,
WarActionPlayerVoteForDraw = 24,
WarActionUnitWait = 30,
WarActionUnitBeLoaded = 31,
WarActionUnitCaptureTile = 32,
WarActionUnitAttackTile = 33,
WarActionUnitAttackUnit = 34,
WarActionUnitDropUnit = 35,
WarActionUnitBuildTile = 36,
WarActionUnitDive = 37,
WarActionUnitSurface = 38,
WarActionUnitJoinUnit = 39,
WarActionUnitLaunchFlare = 40,
WarActionUnitLaunchSilo = 41,
WarActionUnitProduceUnit = 42,
WarActionUnitSupplyUnit = 43,
WarActionUnitLoadCo = 44,
WarActionUnitUseCoSkill = 45,
}}
